### DISCUSSION TITLE
Customizing Navbar with backdrop-filter

### DISCUSSION THREAD

**Discussion by aozaki-kuro** [facebook/docusaurus#6853] [Q&A] [answered]
I bumped into some problems with the navbar customization and looking for help 😢

### Custom CSS

I added extra options for `.navbar`
```css
.navbar {
    ...
    background: rgb(255 255 255 / 65%);
    backdrop-filter: blur(20px);
}
```

---

### Before
![image](https://user-images.githubusercontent.com/28428951/156906937-e96e45da-5bce-4bfa-997d-a564522d633f.png)

### After
![image](https://user-images.githubusercontent.com/28428951/156906957-f013e24d-d5ab-4a0a-a607-200017fb4bcf.png)

---

### Mobile Navbar

It is working great on desktop but the mobile navbar got affected like this
![image](https://user-images.githubusercontent.com/28428951/156907019-354607bd-e31e-4953-a3c1-48e94cfcb86e.png)

I have upgraded to 2.0.0-beta.17 and the problem still exists.

I'm not sure how to solve the problem, any help will be appreciated 😭
