### DISCUSSION TITLE
Search box misaligned since beta 20

### DISCUSSION THREAD

**Discussion by sivaraam** [facebook/docusaurus#7536] [Q&A] [answered]
I'm using the [cmfcmf/docusaurus-search-local](https://github.com/cmfcmf/docusaurus-search-local) plugin for search in the docusaurus website. Once I upgraded to beta 20, I noticed that the search bar became misaligned [[related issue](https://github.com/cmfcmf/docusaurus-search-local/issues/117)]. On exploring, it turns out disabling the following CSS rule fixes the misalignment [[source](https://github.com/facebook/docusaurus/blob/fe064a87a6d6a2695ab78001c514913e902cb5c3/packages/docusaurus-theme-classic/src/theme/Navbar/Search/styles.module.css)]

```css
@media (min-width: 997px) {
  .searchBox {
    padding: var(--ifm-navbar-item-padding-vertical)
      var(--ifm-navbar-item-padding-horizontal);
  }
}
```

For now, I've worked around this using the following CSS snippet in the `src/pages/styles.module.css` file:

```css
@media (min-width: 997px) {
  [class^="searchBox"] {
    padding: unset;
  }
}
```

Any hints on the right way to fix this issue would be very helpful.

## Screenshots

**With v2.0.0-beta.18**

![image](https://user-images.githubusercontent.com/12448084/171137131-21fd119a-f659-4791-8677-12f332cc1d0d.png)

**With v2.0.0-beta.21**

![image](https://user-images.githubusercontent.com/12448084/171136945-2e9b3d59-ef2b-4d55-abb0-1bf4e9f5fbd9.png)

**With v2.0.0-beta.21 (style disabled)**

![image](https://user-images.githubusercontent.com/12448084/171137424-43b6ebc4-e339-4240-9a22-c0875c723362.png)
