### DISCUSSION TITLE
Hide Announcement Bar in a single page

### DISCUSSION THREAD

**Discussion by ccamusso** [facebook/docusaurus#7695] [Q&A] [answered]
Is it possible enable Announcement Bar but hide it on a specific page?

**Comment by slorber** [comment, marked as answer]
Yes

Solution 1: swizzle the announcement bar, use React-Router `useLocation()` hook and render nothing when your condition is met

Solution 2: use CSS classes added to the `<HTML>` element to hide the announcement bar for specific pages/docs

```css
html.docs-wrapper.docs-doc-id-introduction div[class*="announcementBar"] {
  display: none;
}
```
