### DISCUSSION TITLE
Add Icons to Navbar

### DISCUSSION THREAD

**Discussion by reeceatkinson** [facebook/docusaurus#7857] [Q&A] [answered]
I have the nav bar configured in the docusaurus.config.js file. However I was wondering how I can add a icon like and <img> or <svg> to the nav items. When I tried to add an image (as I expected) this happened.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/78908925/182030600-11e5d08f-98a7-4f10-ade0-38dc08f160f9.png">

**Comment by pranabdas** [comment, marked as answer]
Are you trying to add Logo icon? You can pass:
```
navbar: {
  title: "My website title",
  hideOnScroll: true,
  logo: {
    alt: "Logo",
    src: "img/favicon.ico",
  },
...
}
```

You can also add icon to any navbar item by targeting CSS. Here is a Nav item with classname `header-github-link`:
```
{
  href: 'https://github.com/facebook/docusaurus',
  position: 'right',
  className: 'header-github-link',
  'aria-label': 'GitHub repository',
},
```

Then you can apply style in your `custom.css`:
```css
.header-github-link:hover {
  opacity: 0.6;
}

.header-github-link::before {
  content: '';
  width: 24px;
  height: 24px;
  display: flex;
  background: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'/%3E%3C/svg%3E")
    no-repeat;
}

[data-theme='dark'] .header-github-link::before {
  background: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill='white' d='M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'/%3E%3C/svg%3E")
    no-repeat;
}
```
Above examples are taken from Docusaurus website: 
- https://github.com/facebook/docusaurus/blob/main/website/docusaurus.config.js#L504
- https://github.com/facebook/docusaurus/blob/main/website/src/css/custom.css#L72

**Reply by reeceatkinson** [reply]
No, 
Basically I want the Docs, Blog and Hire Me nav items to have a image / icon next to them
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/78908925/182164138-0852ffde-2371-4b25-9fda-efc264e04910.png">

**Reply by pranabdas** [reply]
I think it should be possible with CSS. You pass a `className` to your navbar item, and use it to style:
```css
.doc-icon {
  padding-left: 32px;
  width: 16px;
  height: 16px;
  display: inline;
  background: url("/img/favicon.ico") no-repeat;
}
```
My example CSS does not scale the image properly, you need to find the correct css rules to make it work properly. 

PS: if you are ok with emoji, you can use them along with the text. Much easier.
