### DISCUSSION TITLE
How to display Excalidraw font Virgil properly in a docusaurus page?

### DISCUSSION THREAD

**Discussion by tisonkun** [facebook/docusaurus#8021] [Q&A] [answered]
I try to add:

```css
      @font-face {
        font-family: "Virgil";
        src: url("https://excalidraw.com/Virgil.woff2");
      }
      @font-face {
        font-family: "Cascadia";
        src: url("https://excalidraw.com/Cascadia.woff2");
      }
```

in the `custom.css` file or download the woff2 files and link them as static assets. But still, the font doesn't display properly.

I read https://docusaurus.io/docs/next/markdown-features/assets#images but it seems not to work for me.

Here is the exported SVG you can play with:

![pulsar-scenario-cdc](https://user-images.githubusercontent.com/18818196/187356296-4598841f-c34b-4131-b0cf-3f8387ac1d5f.svg)

NOTE: The font cannot render on GitHub also.

Reference issue: https://github.com/tisonkun/pulsar-planet/issues/1
