### DISCUSSION TITLE
How to add more icons on navbar?

### DISCUSSION THREAD

**Discussion by RudraSen2** [facebook/docusaurus#8130] [Q&A]
I saw the docusaurus site and copied the code for the GitHub icon in the navbar to my website. Can you tell me how to put more icons as I'm unable to do so by converting the image to base64? The base64 image that I put always shows blank. I'll tell you how:

- **Docusaurus GitHub Icon Code:**
```css
.header-github-link:hover {
  opacity: 0.6;
}

.header-github-link:before {
  content: "";
  width: 24px;
  height: 24px;
  display: flex;
  background: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'/%3E%3C/svg%3E") no-repeat;
}

html[data-theme="dark"] .header-github-link:before {
  background: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill='white' d='M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'/%3E%3C/svg%3E") no-repeat;
}
```

- **My YouTube Icon Code:**

```css
.header-youtube-link:hover {
  opacity: 0.6;
}

.header-youtube-link:before {
  content: "";
  width: 24px;
  height: 24px;
  display: flex;
  background: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAMAAADDpiTIAAAAA3NCSVQICAjb4U/gAAAACXBIWXMAAA9fAAAPXwHXitrJAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAqxQTFRF////9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwNDhRLyAAAAON0Uk5TAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUnKCkqKywtLzAxMjM0NTY3ODk7PD0+P0FCQ0RFRkhJSktMTU5PUFFTVFVXWFlaW11eX2BhYmRlZ2hpa2xtb3BxcnN0dXZ3eXp7fH1/gIOEhYaHiYqMjY6PkJGSk5SVlpeYmpucnp+goqOkpaanqKmrrK2ur7CxsrO0tre4ubq7vL2+v8DBwsTFxsfIycrLzc7P0NHT1NXW2Nna29zd3t/g4eLj5OXm5+jp6uvs7e/w8fLz9PX29/j5+vv8/f4FCqEUAAANL0lEQVQYGe3BiWPWd30H8HcOrlgguHBH2DgCUiNmgG2hgJPBuqUoFmdhFObGwCGMgUIddMxyzCZzpbETxlXClwpNY1cdAnJIMaQyE7PQUcCEHDzJ+x+ZkVIC5HieJ8/x+/y+79cLIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhIgWUPzC6ZIlAryh2bBvuzJi9buLjvy9unLdY2UGDXWXT799pGy3WsXTc6GNSNmr9h2+FIrJSFaLx3etmL2CNgwfvneGkoS1OxdPh7BNuq5kiuUJLpS8twoBFP2wp0XKSlwcefCbATN9B31lJSp3zEdATJm3XlKip1fNwaBkLP0eISSBpHjS3OQbvkv36Kkza2X85FOE0taKGnVUjIR6TKtLEJJu0jZNKRD0YF2SiC0HyhCqs1ylAA5NguplFfaTgmU9tI8pErmyuuUwLm+MhMpUXSKEkinipB8w/a0UQKqbc8wJFfGsmuUALu2LANJlFdOCbjyPCTN7BpK4NXMRnJkbIhQDIhsyEASDHcUI9xwJNycWooZtXOQWJkbIxRDIhszkUADD1GMOTQQCTO0kmJO5VAkyKhzFIPOjUJCTKqmmFQ9CQkwvZ5iVP109NncmxSzbs5FHy1uphjWvBh9UhyhmBYpRh/MaaIY1zQHcSu8QTHvRiHiNKGOEgJ1ExCXkVWUUKgaiTgMOUMJiTNDELMBFZTQqBiAWO2jhMg+xGgNJVTWICYzWymh0joTMch9nxIy7+ciegcpoXMQUVtNCaHViNKMFkoItcxAVHKrKaFUnYto7KeE1H5EoZgSWs+iVzlXKaF1NQe9eZESYi+iFwUtlBBrKUDPTlBC7QR6tIQSckvQg8G1lJCrHYzuvUQJvZfQrSl3KKF3Zwq68xrFA6+hGxMjFA9EJqJrpRQvlKJL41opXmgdh67sonhiF7owuoniiabReNR2ije24xF5DRRvNOThYVsoHtmCh2TVUTxSl4UHLaB4ZQEeVEbxShkeMLiR4pXGwejseYpnnkdnJymeOYlO8tsonmnLx33rKd5Zj/suULxzAR8rpHioEPeso3hoHe45RvHQMXykXwPFQw39cNeTFC89ibs2Uby0CXdVULxUgd8b1EzxUvMgdJhP8dR8dNhK8dRWdHiX4ql30aGB4qkG/M5YirfGAphH8dY8AKso3loFYAfFWzsAlFO8VQ6giuKtKqB/hOKtSH9MpXhsKoopHivGGorH1mAzxWObsZ3ise14heKxV/A6xWOv4yjFY0dRSfFYJc5SPHYWVRSPVaGe4rF63KZ47DZo2tkfN1D6ArSrbeN4IPPx7zZR4gaa1b4cd43Z1UyJE2jWFnzsU//aSokLaFYhOhlfcocSB9Cq+gw8YMK/3aHEDLTqTTxs0qsRSoxAqxweVVDWRokJaJVDV6b+sJ0SA9Aqh649vr+dEjXQKofuFB6kRAu0yqF7n3uDEh3QKoeezCinRAO0yqFnn3+T0jvQKofePHWS0hvQKofePV1J6RlolUM05r1D6QlolUN0vvgTSvdAqxyi9aenKN0BrXKI3jOnKV0DrXKIRfHPKV0BrXKIScbi85RHgVY5xChjyS8oDwOtcohZ5tL3KA8CrXKIQ9bXfknpDLTKIS7Zy6sp94FWOcSp3wu/otwDWuUQt/6rfk25C7TKoQ8GfL2W0gG0yqFPBq6uo5CgVQ59NGhtPQW0yqHPcr75AX0HWuWQAI9tuE6/gVY5JMTgTR/SZ6BVDgky9Fs36C/QKoeEGfbtW/QVaJVDAv3BdxroJ9Aqh4Qavq2RPgKtckiwkf98m/4BrXJIuNHfbaZvQKsckmDs7hb6BbTKISk+9b1W+gS0yiFJxpfcoT9AqxySZsL3I/QFaJVDEk16NUI/gFY5JFXBD9roA9AqhyT79A/bGX6gVQ5J95n/bGfYgVY5pMBnDzHkQKscUqLoDYYaaJVDisw8xhADrXJImSfeZGiBVjmk0FNvMaRAqxxS6ulKhhJolUOKzX+HIQRa5ZByX/wpQwe0yiENFv6MIQNa5ZAWz5xhqIBWOaRHxrPnGCKgVQ7pkvGlCwwN0CqH9Mlc8guGBGiVQzplfvU9hgJolUN6ZX2tiiEAWuWQbtl/VU3zQKsc0q/fC1dpHGiVQxD0/+tf0zTQKodgGPA3tTQMtMohKAaurqNZoFUOwTHoG/U0CrTKIUg+8c0PaBJolUOwPPYP12kQaJVD0AzZ9CHNAa1yCJ7ct2gNaJVDAA08SmNAqxyCqN/PaQtolUMgbaUtoFUOgTSftoBWOQTSZNoCWuUQSKtoC2iVQyAdoi2gVQ5B9GfNtAW0yiGAVkRoDGiVQ+BMKKU5oFUOAfN4WYT2gFY5BMqsw+20CLTKIUDmnaBRoFUOQZHx5z+lWaBVDsGQtfQ8DQOtcgiC/i9U0TTQKof0+8SaWhoHWuWQbsM2/R/NA61ySK+R/3SLIQBa5ZBO43c3MRRAqxzSZ8q/32FIgFY5pMvn9rcxNECrHNJjjmOYgFY5pMPCdxguoFUOKZf55bMMG9AqhxTrt/w9hg9olUNKDfrb/2EYgVY5pNCQDfUMJ9Aqh5QZvuUGwwq0yiFF8v+lkeEFWuWQEpNLWxhmoFUOKVD4H20MN9Aqh6R74g2GHmiVQ5L9SQU9AFrlkEwZz/6MXgCtckie7L+8SE+AVjkky4BV1fQGaJVDcjz297+hR0CrHJLhk9+6Tq+AVjkk3ujtv6VnQKscEu2PvtdM74BWOSTWtL0Regi0yiGRZhxsp5dAqxwSZ+6P6CvQKocEyXjmJ/QXaJVDQmR95Rx9BlrlkAD9V/ySfgOtcuiznL+roe9Aqxz6KPcfP6CAVjn0yYjv3KSQoFUOfTBu521KB9Aqh7gVfL+VchdolUOcpu9ro9wDWuUQl6fKKZ2AVjnEYcGPKQ8ArXKIVeaXTlMeAlrlEJt+yy5RHgFa5RCLgV//FaULoFUO0Ruy/n8pXQKtcohW3rc/pHQDtMohOmN3NFK6BVrlEI1JJS2UHoBWOfTuMz+IUHoEWuXQm88faaf0ArTKoWdfeIvSO9Aqhx5k/MV/U6IBWuXQrayvXqBEB7TKoRsDVl6hRAu0yqFLj33jN5TogVY5dGHY5uuUWIBWOTxi1LbfUmIDWnUZD/nDPU2UWIFm5aOzT796hxI70KzluO+PD7RT4gGa9eFn8ZGnj1PiBNp17Ql0WPRflLiBllVt23K0ltIHuE3x2G3UUzxWjyqKx6pwluKxs6ikeKwSRykeO4rXKR57Ha9QPPYKtlM8th2bKR7bjDUUj61BMcVjxZhK8dhU9I9QvBXpD1RRvFUFoJzirXIAOyje2gFgFcVbqwDMo3hrHoCxFG+Nxe80UDzVgA7vUjz1LjpspXhqKzrMp3hqPjoMaqZ4qXkQfq+C4qUK3LWJ4qVNuOtJipeexF39GigeauiHjxyjeOgY7llH8dA63FNI8VAhPnaB4p0LuG89xTvrcV9+G8Uzbfno5CTFMyfR2fMUzzyPzgY3UrzSOBgPKKN4pQwPWkDxygI8KKuO4pG6LDxkC8UjW/CwvAaKNxry8IjtFG9sx6NGN1E80TQaXdhF8cQudGVcK8ULrePQpVKKF0rRtYkRigciE9GN1ygeeA3dmXKHEnp3pqBbL1FC7yV0b3AtJeRqB6MHSyghtwQ9OkEJtRPoWUELJcRaCtCLFykh9iJ6k3OVElpXc9CrYkpoPYso7KeE1H5EI7eaEkrVuYjKjBZKCLXMQJRWU0JoNaJ2kBI6BxG93PcpIfN+LmIws5USKq0zEZM1lFBZgxjto4TIPsRqQAUlNCoGIGZDzlBC4swQxGFkFSUUqkYiLhPqKCFQNwFxKrxBMe9GIeI2p4liXNMc9EFxhGJapBh9sriZYljzYvTR3JsUs27ORZ9Nr6cYVT8dCTCpmmJS9SQkxKhzFIPOjUKCDK2kmFM5FAkz8BDFmEMDkUCZGyMUQyIbM5FYc2opZtTOQcINdxQj3HAkQcaGCMWAyIYMJMfsGkrg1cxG0uSVUwKuPA9JlLHsGiXAri3LQHIN29NGCai2PcOQfEWnKIF0qggpkbnyOiVwrq/MRKrklbZTAqW9NA+pNMtRAuTYLKRa0YF2SiC0HyhCOkwri1DSLlI2DekysaSFklYtJRORTvkv36Kkza2X85FuOUuPRyhpEDm+NAeBMGbdeUqKnV83BgEyfUc9JWXqd0xH0GQv3HmRkgIXdy7MRjCNeq7kCiWJrpQ8NwrBNn753hpKEtTsXT4eNoyYvWLb4UutlIRovXR424rZI2BN9uRFa3eXHXn79OW6RkqMGusun377SNnutYsmZ8O+rKH5BVMkSgX5Q7MgIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIsHx/8bGbtVDO+ktAAAAAElFTkSuQmCC") no-repeat;
}

html[data-theme="dark"] .header-youtube-link:before {
  background: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAMAAADDpiTIAAAAA3NCSVQICAjb4U/gAAAACXBIWXMAAA9fAAAPXwHXitrJAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAqxQTFRF////9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwN9hwNDhRLyAAAAON0Uk5TAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUnKCkqKywtLzAxMjM0NTY3ODk7PD0+P0FCQ0RFRkhJSktMTU5PUFFTVFVXWFlaW11eX2BhYmRlZ2hpa2xtb3BxcnN0dXZ3eXp7fH1/gIOEhYaHiYqMjY6PkJGSk5SVlpeYmpucnp+goqOkpaanqKmrrK2ur7CxsrO0tre4ubq7vL2+v8DBwsTFxsfIycrLzc7P0NHT1NXW2Nna29zd3t/g4eLj5OXm5+jp6uvs7e/w8fLz9PX29/j5+vv8/f4FCqEUAAANL0lEQVQYGe3BiWPWd30H8HcOrlgguHBH2DgCUiNmgG2hgJPBuqUoFmdhFObGwCGMgUIddMxyzCZzpbETxlXClwpNY1cdAnJIMaQyE7PQUcCEHDzJ+x+ZkVIC5HieJ8/x+/y+79cLIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhIgWUPzC6ZIlAryh2bBvuzJi9buLjvy9unLdY2UGDXWXT799pGy3WsXTc6GNSNmr9h2+FIrJSFaLx3etmL2CNgwfvneGkoS1OxdPh7BNuq5kiuUJLpS8twoBFP2wp0XKSlwcefCbATN9B31lJSp3zEdATJm3XlKip1fNwaBkLP0eISSBpHjS3OQbvkv36Kkza2X85FOE0taKGnVUjIR6TKtLEJJu0jZNKRD0YF2SiC0HyhCqs1ylAA5NguplFfaTgmU9tI8pErmyuuUwLm+MhMpUXSKEkinipB8w/a0UQKqbc8wJFfGsmuUALu2LANJlFdOCbjyPCTN7BpK4NXMRnJkbIhQDIhsyEASDHcUI9xwJNycWooZtXOQWJkbIxRDIhszkUADD1GMOTQQCTO0kmJO5VAkyKhzFIPOjUJCTKqmmFQ9CQkwvZ5iVP109NncmxSzbs5FHy1uphjWvBh9UhyhmBYpRh/MaaIY1zQHcSu8QTHvRiHiNKGOEgJ1ExCXkVWUUKgaiTgMOUMJiTNDELMBFZTQqBiAWO2jhMg+xGgNJVTWICYzWymh0joTMch9nxIy7+ciegcpoXMQUVtNCaHViNKMFkoItcxAVHKrKaFUnYto7KeE1H5EoZgSWs+iVzlXKaF1NQe9eZESYi+iFwUtlBBrKUDPTlBC7QR6tIQSckvQg8G1lJCrHYzuvUQJvZfQrSl3KKF3Zwq68xrFA6+hGxMjFA9EJqJrpRQvlKJL41opXmgdh67sonhiF7owuoniiabReNR2ije24xF5DRRvNOThYVsoHtmCh2TVUTxSl4UHLaB4ZQEeVEbxShkeMLiR4pXGwejseYpnnkdnJymeOYlO8tsonmnLx33rKd5Zj/suULxzAR8rpHioEPeso3hoHe45RvHQMXykXwPFQw39cNeTFC89ibs2Uby0CXdVULxUgd8b1EzxUvMgdJhP8dR8dNhK8dRWdHiX4ql30aGB4qkG/M5YirfGAphH8dY8AKso3loFYAfFWzsAlFO8VQ6giuKtKqB/hOKtSH9MpXhsKoopHivGGorH1mAzxWObsZ3ise14heKxV/A6xWOv4yjFY0dRSfFYJc5SPHYWVRSPVaGe4rF63KZ47DZo2tkfN1D6ArSrbeN4IPPx7zZR4gaa1b4cd43Z1UyJE2jWFnzsU//aSokLaFYhOhlfcocSB9Cq+gw8YMK/3aHEDLTqTTxs0qsRSoxAqxweVVDWRokJaJVDV6b+sJ0SA9Aqh649vr+dEjXQKofuFB6kRAu0yqF7n3uDEh3QKoeezCinRAO0yqFnn3+T0jvQKofePHWS0hvQKofePV1J6RlolUM05r1D6QlolUN0vvgTSvdAqxyi9aenKN0BrXKI3jOnKV0DrXKIRfHPKV0BrXKIScbi85RHgVY5xChjyS8oDwOtcohZ5tL3KA8CrXKIQ9bXfknpDLTKIS7Zy6sp94FWOcSp3wu/otwDWuUQt/6rfk25C7TKoQ8GfL2W0gG0yqFPBq6uo5CgVQ59NGhtPQW0yqHPcr75AX0HWuWQAI9tuE6/gVY5JMTgTR/SZ6BVDgky9Fs36C/QKoeEGfbtW/QVaJVDAv3BdxroJ9Aqh4Qavq2RPgKtckiwkf98m/4BrXJIuNHfbaZvQKsckmDs7hb6BbTKISk+9b1W+gS0yiFJxpfcoT9AqxySZsL3I/QFaJVDEk16NUI/gFY5JFXBD9roA9AqhyT79A/bGX6gVQ5J95n/bGfYgVY5pMBnDzHkQKscUqLoDYYaaJVDisw8xhADrXJImSfeZGiBVjmk0FNvMaRAqxxS6ulKhhJolUOKzX+HIQRa5ZByX/wpQwe0yiENFv6MIQNa5ZAWz5xhqIBWOaRHxrPnGCKgVQ7pkvGlCwwN0CqH9Mlc8guGBGiVQzplfvU9hgJolUN6ZX2tiiEAWuWQbtl/VU3zQKsc0q/fC1dpHGiVQxD0/+tf0zTQKodgGPA3tTQMtMohKAaurqNZoFUOwTHoG/U0CrTKIUg+8c0PaBJolUOwPPYP12kQaJVD0AzZ9CHNAa1yCJ7ct2gNaJVDAA08SmNAqxyCqN/PaQtolUMgbaUtoFUOgTSftoBWOQTSZNoCWuUQSKtoC2iVQyAdoi2gVQ5B9GfNtAW0yiGAVkRoDGiVQ+BMKKU5oFUOAfN4WYT2gFY5BMqsw+20CLTKIUDmnaBRoFUOQZHx5z+lWaBVDsGQtfQ8DQOtcgiC/i9U0TTQKof0+8SaWhoHWuWQbsM2/R/NA61ySK+R/3SLIQBa5ZBO43c3MRRAqxzSZ8q/32FIgFY5pMvn9rcxNECrHNJjjmOYgFY5pMPCdxguoFUOKZf55bMMG9AqhxTrt/w9hg9olUNKDfrb/2EYgVY5pNCQDfUMJ9Aqh5QZvuUGwwq0yiFF8v+lkeEFWuWQEpNLWxhmoFUOKVD4H20MN9Aqh6R74g2GHmiVQ5L9SQU9AFrlkEwZz/6MXgCtckie7L+8SE+AVjkky4BV1fQGaJVDcjz297+hR0CrHJLhk9+6Tq+AVjkk3ujtv6VnQKscEu2PvtdM74BWOSTWtL0Regi0yiGRZhxsp5dAqxwSZ+6P6CvQKocEyXjmJ/QXaJVDQmR95Rx9BlrlkAD9V/ySfgOtcuiznL+roe9Aqxz6KPcfP6CAVjn0yYjv3KSQoFUOfTBu521KB9Aqh7gVfL+VchdolUOcpu9ro9wDWuUQl6fKKZ2AVjnEYcGPKQ8ArXKIVeaXTlMeAlrlEJt+yy5RHgFa5RCLgV//FaULoFUO0Ruy/n8pXQKtcohW3rc/pHQDtMohOmN3NFK6BVrlEI1JJS2UHoBWOfTuMz+IUHoEWuXQm88faaf0ArTKoWdfeIvSO9Aqhx5k/MV/U6IBWuXQrayvXqBEB7TKoRsDVl6hRAu0yqFLj33jN5TogVY5dGHY5uuUWIBWOTxi1LbfUmIDWnUZD/nDPU2UWIFm5aOzT796hxI70KzluO+PD7RT4gGa9eFn8ZGnj1PiBNp17Ql0WPRflLiBllVt23K0ltIHuE3x2G3UUzxWjyqKx6pwluKxs6ikeKwSRykeO4rXKR57Ha9QPPYKtlM8th2bKR7bjDUUj61BMcVjxZhK8dhU9I9QvBXpD1RRvFUFoJzirXIAOyje2gFgFcVbqwDMo3hrHoCxFG+Nxe80UDzVgA7vUjz1LjpspXhqKzrMp3hqPjoMaqZ4qXkQfq+C4qUK3LWJ4qVNuOtJipeexF39GigeauiHjxyjeOgY7llH8dA63FNI8VAhPnaB4p0LuG89xTvrcV9+G8Uzbfno5CTFMyfR2fMUzzyPzgY3UrzSOBgPKKN4pQwPWkDxygI8KKuO4pG6LDxkC8UjW/CwvAaKNxry8IjtFG9sx6NGN1E80TQaXdhF8cQudGVcK8ULrePQpVKKF0rRtYkRigciE9GN1ygeeA3dmXKHEnp3pqBbL1FC7yV0b3AtJeRqB6MHSyghtwQ9OkEJtRPoWUELJcRaCtCLFykh9iJ6k3OVElpXc9CrYkpoPYso7KeE1H5EI7eaEkrVuYjKjBZKCLXMQJRWU0JoNaJ2kBI6BxG93PcpIfN+LmIws5USKq0zEZM1lFBZgxjto4TIPsRqQAUlNCoGIGZDzlBC4swQxGFkFSUUqkYiLhPqKCFQNwFxKrxBMe9GIeI2p4liXNMc9EFxhGJapBh9sriZYljzYvTR3JsUs27ORZ9Nr6cYVT8dCTCpmmJS9SQkxKhzFIPOjUKCDK2kmFM5FAkz8BDFmEMDkUCZGyMUQyIbM5FYc2opZtTOQcINdxQj3HAkQcaGCMWAyIYMJMfsGkrg1cxG0uSVUwKuPA9JlLHsGiXAri3LQHIN29NGCai2PcOQfEWnKIF0qggpkbnyOiVwrq/MRKrklbZTAqW9NA+pNMtRAuTYLKRa0YF2SiC0HyhCOkwri1DSLlI2DekysaSFklYtJRORTvkv36Kkza2X85FuOUuPRyhpEDm+NAeBMGbdeUqKnV83BgEyfUc9JWXqd0xH0GQv3HmRkgIXdy7MRjCNeq7kCiWJrpQ8NwrBNn753hpKEtTsXT4eNoyYvWLb4UutlIRovXR424rZI2BN9uRFa3eXHXn79OW6RkqMGusun377SNnutYsmZ8O+rKH5BVMkSgX5Q7MgIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIsHx/8bGbtVDO+ktAAAAAElFTkSuQmCC") no-repeat;
}
```

---

- **`docusaurus.config.js`**

```js
// GitHub
            {
              href: "https://github.com/Comp-Labs",
              position: "right",
              className: "header-github-link",
              "aria-label": "GitHub",
            },
// YouTube
            {
            href: "https://youtube.com/channel/UCL6pKeSCbJkPohM2PUZbqQA",
            position: "right",
            className: "header-youtube-link",
            "aria-label": "YouTube",
            },
```

Please tell me how to do this as I want to put more icons other than YouTube and GitHub... Any help would be appreciated!
