### DISCUSSION TITLE
How to update default classic theme to avoid appending icon to external links?

### DISCUSSION THREAD

**Discussion by dcs3spp** [facebook/docusaurus#8547] [Q&A] [answered]
Hi,

I have searched the [documentation](https://docusaurus.io/) but cannot seem to find how to change the style of external links in the docusaurus classic-theme. Is this possible?

Inspecting the block element in Firefox shows that all external links in navbar and footer are appended with an icon.

```
##a.navbar__link.navbar__item > .iconExternalLink_node_modules-\@docusaurus-theme-classic-lib-theme-Icon-ExternalLink-styles-module
```

How do I change the default behaviour of the [classic-theme](https://docusaurus.io/docs/api/themes/@docusaurus/theme-classic) to avoid appending the external link icon?

**Comment by slorber** [comment, marked as answer]
You can swizzle the theme components or provide custom CSS to hide things you don't like. There's no first-class config option for every single possible UI customization because everyone want something slightly different.

**Comment by triplef** [comment]
Adding this to my `custom.css` worked for me to remove the external link icon:

```css
.iconExternalLink_node_modules-\@docusaurus-theme-classic-lib-theme-Icon-ExternalLink-styles-module {
  display: none;
}
```

**Reply by slorber** [reply]
I wouldn't recommend that, most likely it only works in development, because the prod className will contain a hash instead of a readable CSS module name (`iconExternalLink_Rdzz` for example)

Swizzle is the way

Alternatively, you can use a CSS class prefix selector:

```css
[class*='iconExternalLink_'] {
  display: none;
}
```

See also https://docusaurus.io/docs/next/styling-layout#global-styles
