### DISCUSSION TITLE
Configurable top left link?

### DISCUSSION THREAD

**Discussion by ilg-ul** [facebook/docusaurus#8762] [Q&A] [answered]
I have a use case a bit more complicated than usual, I have a top project web and a lot (tens) of sub-projects, each with it's own web, all looking the same.

For consistency reasons, all webs have the same logo and the name of the top project in the top left corner.

For example, a mock project:

![Screenshot 2023-03-12 at 18 02 46](https://user-images.githubusercontent.com/362732/224563238-405b8b9d-66b8-4728-bffb-6b27b528e381.png)

In Docusaurus I was able to configure the logo and the label, but I did not find an easy way to configure the link behind these elements, they point to the current project, while I would like to point to the top project.

Any suggestion how to configure this link?

**Comment by pranabdas** [comment, marked as answer]
You can provide `href` and `target` property to logo item in `docusaurus.config.js`:

```js
navbar: {
  title: 'My Site',
  logo: {
    alt: 'My Site Logo',
    src: 'img/logo.svg',
    href: 'https://example.com',
    target: '_self',
  },
  ...
}
```

**Reply by ilg-ul** [reply]
Great advice, it works as expected!

Thank you!

**Comment by ilg-ul** [comment]
Is it possible to add a Home icon to the next link, which now shows only the text **Home**?

**Comment by pranabdas** [comment]
Easy way is to use emoji :house: Alternatively, you can target particular nav item using `className`, and use CSS to decorate icon.

**Reply by ilg-ul** [reply]
>  target particular nav item using className, and use CSS to decorate icon

I think this is a nice solution, a site with emojis does not look serious.

Can you provide an example? (my knowledge of css/react leaves a lot to be desired...)

**Reply by pranabdas** [reply]
You may check out the GitHub icon in <https://docusaurus.io> website [config](
https://github.com/facebook/docusaurus/blob/main/website/docusaurus.config.js#L540) and [CSS](
https://github.com/facebook/docusaurus/blob/main/website/src/css/custom.css#L78).

**Reply by ilg-ul** [reply]
Thank you @pranabdas, that was helpful.

I could not align the icon with the label, so I disabled the label, it was redundant anyway.

The result is somehow consistent with the home icon present in the docs pages as breadcrumbs:

![Screenshot 2023-03-13 at 20 18 17](https://user-images.githubusercontent.com/362732/224795937-b4af082a-f664-41a6-afc6-845894d12585.png)

In case someone else will need this solution, this is the CSS:

```css
.header-home-link::before {
  content: '';
  width: 24px;
  height: 24px;
  display: inline-flex;
  vertical-align: middle;
  /* padding-right: 0.5em; */
  background: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M10 19v-5h4v5c0 .55.45 1 1 1h3c.55 0 1-.45 1-1v-7h1.7c.46 0 .68-.57.33-.87L12.67 3.6c-.38-.34-.96-.34-1.34 0l-8.36 7.53c-.34.3-.13.87.33.87H5v7c0 .55.45 1 1 1h3c.55 0 1-.45 1-1z' fill='current-color'/%3E%3C/svg%3E")
    no-repeat;
}

[data-theme='dark'] .header-home-link::before {
  content: '';
  width: 24px;
  height: 24px;
  display: inline-flex;
  vertical-align: middle;
  /* padding-right: 0.5em; */
  background: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M10 19v-5h4v5c0 .55.45 1 1 1h3c.55 0 1-.45 1-1v-7h1.7c.46 0 .68-.57.33-.87L12.67 3.6c-.38-.34-.96-.34-1.34 0l-8.36 7.53c-.34.3-.13.87.33.87H5v7c0 .55.45 1 1 1h3c.55 0 1-.45 1-1z' fill='white'/%3E%3C/svg%3E")
    no-repeat;
}
```
