### DISCUSSION TITLE
deploy docusaurs projecto to kubernetes

### DISCUSSION THREAD

**Discussion by AnaSofia94** [facebook/docusaurus#8856] [Q&A]
Hello, 
I have a docusaurs project and I want to deploy to kubernetes, but I have this error:Error: validation: chart.metadata is required.
Do you know what's this related to?

**Comment by Advait251206** [comment]
That error is not coming from Docusaurus itself — it’s coming from **Helm/Kubernetes chart validation**.

### What the error means
> `Error: validation: chart.metadata is required`

This happens when you try to install or package a Helm chart, but the chart structure is invalid.

In a valid Helm chart, you MUST have:

```
my-chart/
  Chart.yaml   ← REQUIRED (this is where metadata lives)
  values.yaml
  templates/
```

Inside `Chart.yaml`, you need metadata like:

```yaml
apiVersion: v2
name: docusaurus-site
version: 0.1.0
description: Docusaurus static site deployment
```

If `Chart.yaml` is missing or malformed, Helm throws exactly this error.

---

### Why it’s happening in your case

You likely tried one of these:

- `helm install ...` on a folder that is NOT a proper Helm chart
- Or you pointed Helm to your **Docusaurus project root** instead of a chart directory
- Or `Chart.yaml` exists but is empty / incorrectly named / wrong indentation

---

### Correct way to deploy Docusaurus on Kubernetes

Docusaurus is a **static site**, so you must:

1. Build it:
```bash
npm run build
```

This generates:
```
build/
```

2. Serve it via a web server (commonly nginx)

3. Containerize it:

**Dockerfile example:**
```dockerfile
FROM nginx:alpine
COPY build /usr/share/nginx/html
```

4. Then create a proper Helm chart OR plain Kubernetes manifests:

**Deployment example:**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docusaurus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docusaurus
  template:
    metadata:
      labels:
        app: docusaurus
    spec:
      containers:
        - name: nginx
          image: your-image:latest
          ports:
            - containerPort: 80
```

---

### Key fix for your error

If you're using Helm:

✔ Make sure this exists:
```
Chart.yaml
```

✔ Not:
- chart.yaml ❌
- Chart.yml ❌
- inside templates ❌

✔ And must include:
```yaml
apiVersion: v2
name: anything
version: 1.0.0
```

---

### Summary
This is not a Docusaurus issue — it's a **missing or invalid Helm chart metadata file (`Chart.yaml`)**.

---

If this answer helped or pointed you in the right direction, I'd appreciate it if you could mark it as the accepted answer so it's easier for others with the same issue to find.

Also, if you found my contribution useful, I'd appreciate it if you could check out my GitHub profile, follow me, and star any repositories you find interesting.

GitHub: https://github.com/Advait251206
