### DISCUSSION TITLE
How to apply i18n for autogenerated sidebar `_category_.yml` label?

### DISCUSSION THREAD

**Discussion by Ikalli** [facebook/docusaurus#8986] [Q&A]
I am currently internationalizing (i18n) a document written in Korean into English.

The sidebar of my document is all autogenerated sidebar.

```js
// sidebar.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  exampleSidebar: [{ type: 'autogenerated', dirName: 'example-dir' }],
};

module.exports = sidebars;
```

I have copied the `/docs` subfolders originally written in Korean to `/i18n/en/docusaurus-plugin-content-docs` and I am translating the documents into English. However, even if I change the `label` attribute in `/i18n/en/docusaurus-plugin-content-docs/example-dir/under-example-dir/_category_.yml` to English, it continues to appear in Korean in the sidebar.

```yaml
# /i18n/en/docusaurus-plugin-content-docs/example-dir/under-example-dir/_category_.yml
position: 2
label: 'Example'
collapsible: true
collapsed: false
```

```yaml
# /docs/example-dir/under-example-dir/_category_.yml
position: 2
label: '예제'
collapsible: true
collapsed: false
```

I run docusaurus following step:
1. `yarn dev --locale en`

But in `example-dir` sidebar, it displays Korean, not English. Is there a way to change this to English?

**Comment by Ikalli** [comment]
<img width="292" alt="Screenshot 2023-05-16 at 6 10 25 PM" src="https://github.com/facebook/docusaurus/assets/16658067/28f4bd24-f38d-4f19-8cc7-0d22f693f833">

This is screenshot in my real document and I'm stuck in here. There's no page for that sidebar item.
`label` in `_category_.yml` with English not working.

```yaml
# /i18n/en/docusaurus-plugin-content-docs/organization-and-project/organization/_category_.yml
# Expectation: shows "Organization" as title
position: 2
label: 'Organization'
collapsible: true
collapsed: false
```
