### DISCUSSION TITLE
Changing header font

### DISCUSSION THREAD

**Discussion by sophiakanoa** [facebook/docusaurus#9238] [Q&A]
I am using one font for my primary text font, but want to use a different one for headers. Any ideas on how to achieve this?
<img width="869" alt="image" src="https://github.com/facebook/docusaurus/assets/137461572/d886fb1e-9f57-4f7b-bcd0-453d48ed2170">

**Comment by slorber** [comment]
You can use plain CSS

```css
h1, h2, h3, h4, h5, h6 {
    font-family: cursive;
}
```

This also works:


```css
:root {
  --ifm-heading-font-family: cursive;
}
```

<img width="1415" alt="CleanShot 2023-08-24 at 14 57 32@2x" src="https://github.com/facebook/docusaurus/assets/749374/369a94ca-5996-4f0a-ae9c-23f89210ec56">
