### DISCUSSION TITLE
Classes to target breadcrumbs?

### DISCUSSION THREAD

**Discussion by ZenaMel** [facebook/docusaurus#9411] [Q&A] [answered]
I'm trying to customize the breadcrumbs.

For example, I want to set the font of the label to `bold`.

I tried:

```css
.breadcrumbs__link:not:first-child {
  font-weight: bold;
}
```

but this didn't work.

this also didn't work:

```css
a .breadcrumbs__link > span {
  font-weight: bold;
}
```
