### DISCUSSION TITLE
How to store locally an author image?

### DISCUSSION THREAD

**Discussion by ilg-ul** [facebook/docusaurus#9504] [Q&A] [answered]
When defining an author, the `image_url` property must be an external URL.

I would like to add the image locally, in the `static/img` folder. The only way I could do this was to refer to the image via the external URL. It would be nice to have a more convenient way and use the internal relative URL.

**Comment by slorber** [comment]
This works for me:

```yaml
slorber:
  name: Sébastien Lorber
  title: Docusaurus maintainer, This Week In React editor
  url: https://thisweekinreact.com
  image_url: /img/docusaurus.png
```

<img width="942" alt="CleanShot 2023-11-11 at 17 21 41@2x" src="https://github.com/facebook/docusaurus/assets/749374/5ceafe0f-25c9-409e-9458-a33f97e20bc3">
