### DISCUSSION TITLE
Please note that showLastUpdateTime does not work properly if the build is run with the default GitHub Actions configuration

### DISCUSSION THREAD

**Discussion by ilg-ul** [facebook/docusaurus#9734] [General]
It took me some time to diagnose this, so perhaps this post can help others save some time.

The problem is that the default depth for the `actions/checkout@v4` action is 1 (latest commit only), and in this case `git log` cannot retrieve the dates of previous commits; instead it returns the date of the latest commit (the only one cloned), for all files, and all documentation pages appear to be updated at the same time.

The solution is to clone the repo with the full history:

```yml
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          # Get the full history, required to compute lastUpdatedAt
          fetch-depth: 0
```

It would be nice to have this info in the documentation page:

- https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#showLastUpdateTime
