### ISSUE TITLE
Blog author social platforms shorthands are not normalized for inline authors

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#10417]
### Description

When authors are provided inline (not in `authors.yml`) authors handle/username shorthand are not normalized to full URLs, leading to incorrect links.

### Steps to reproduce

Create a blog post

```yml
slug: first-blog-post
title: First Blog Post
authors: 
  - name: John Doe
    title: Software Engineer
    socials: 
      github: slorber
```

### Expected behavior

The author GitHub icon link should be `https://github.com/slorber` 

### Actual behavior

The author GitHub icon link shouldn't be not `http://localhost:3000/slorber`
