### ISSUE TITLE
SSR hydration errors in base template when using S3 + CloudFront

### ISSUE THREAD

**Issue by AnnaWinnick** [facebook/docusaurus#10625]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When deploying the base template to an S3 bucket with a CloudFront distribution, there are several hydration errors in the console. 

### Reproducible demo

https://github.com/user-attachments/assets/6771b0b0-8581-470c-b9ca-513690e55607

### Steps to reproduce

1. npx create-docusaurus@latest my-website classic
2. create an S3 bucket w/ cloudfront distribution, all defaults ok
     a) enable static website hosting
3. Create a custom error page on the cloudfront distribution 
     a) [forward 403 -> 200 with index.html](https://piotrkrzyzek.com/solved-aws-cloudfront-s3-returns-403-forbidden-error-on-page-refresh/)
4. create a workflow in .github/workflows/deploy.yml (see below)
5. edit the `url` in `docusaurus.config.js` to the same url as cloudfront 
6. push changes to trigger the workflow
7. once the site is up, open the console, navigate to the tutorial page, and hard refresh
    a) note: this error is visible on any page except the home page and only after refresh

```
name: Deploy Test

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-test:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: npm token
        run: |
          <setup npmrc here if needed> 

      - name: Install and Build
        run: |
          npm ci
          npm run-script build -- --dev --no-minify

      - name: Push docs to s3
        run: |
          aws s3 sync --delete build s3://<s3-bucket-name>/

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id <distribution-ID> \
            --paths "/*"
```

### Expected behavior

No hydration errors.

### Actual behavior

[console-hydration-errors-docusaurus.log](https://github.com/user-attachments/files/17548976/console-hydration-errors-docusaurus.log)

### Your environment

- Docusaurus version used: 3.5.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome Version 130.0.6723.70 (Official Build) (arm64)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 14.6.1 (23G93)

### Self-service

- [ ] I'd be willing to fix this bug myself.
