### ISSUE TITLE
Glitchy scroll on mobile

### ISSUE THREAD

**Issue by SimenB** [facebook/Docusaurus#1155]
## 🐛 Bug Report

Scrolling quickly up and down with a menu open on mobile shows the underlying content at the bottom of the viewport. See https://github.com/reduxjs/redux/issues/3292, but this is reproducible on Docusaurus' own website

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yup

## To Reproduce

(Write your steps here:)

1. Chrome 71 (on pixel 3 xl, if it matters), with Duet enabled
1. Open up a menu on e.g. https://docusaurus.io/docs/en/installation.
1. Scroll quickly up and down

## Expected behavior
No glitching

## Actual Behavior

See gif on linked issue.

## Reproducible Demo

This project's own website reproduces for me.

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by fiennyangeln** [comment]
@SimenB I can reproduce the above using iPhone X / 7 (both are Chrome 71) / Firefox desktop mobile mode (since I dont have Pixel3 at hand) but using different steps. So here is what I do to reproduce the gif linked for redux.js.org
1. Click on the API word as shown below 
<img width="453" alt="image" src="https://user-images.githubusercontent.com/24544912/50039002-7cfa8300-0065-11e9-8999-bd0cfa48ad7e.png">
2. Click on the menu bar on the right side
<img width="413" alt="image" src="https://user-images.githubusercontent.com/24544912/50039004-8daaf900-0065-11e9-932a-ee34b4a5e3a3.png">
3. The empty looking site body
<img width="393" alt="image" src="https://user-images.githubusercontent.com/24544912/50039011-aadfc780-0065-11e9-8611-08208ef83b26.png">

Do you think it is similar?

**Comment by shakcho** [comment]
@endiliey The issue has nothing do with Scroll, The Issue is actually 

```html
<nav class="onPageNav"></nav>
```
element has no child element in it, and also 
```html
<div class="tocToggler" id="tocToggler">
    <i class="icon-toc"></i>
</div>
```
is present in the DOM, and beacause of that when someone Clicks on it(**#tocToggler**) toggles **toActive** class and it applies bellow CSS

```CSS
@media only screen and (max-width: 1023px){
.tocActive .onPageNav {
    background: #fff;
    bottom: 0;
    display: block;
    left: 0;
    overflow-y: auto;
    -ms-scroll-chaining: none;
    overscroll-behavior: contain;
    padding: 0 20px;
    position: fixed;
    right: 0;
    top: 148px;
    z-index: 10;
 }
}
```
which renders the White layout on top of the main container, hence the issue is happening when there is not child element in \<nav class="onPageNav">.

I would like to solve the issue,  but I want to know what will be expected behavior. 

One solution I can think of is to not to render the \<div class="tocToggler" id="tocToggler"> if \<nav class="onPageNav"> has no child element in it .

Please let me know if my approach is correct.
