### ISSUE TITLE
Document ids are confusing when using subfolders and versioning

### ISSUE THREAD

**Issue by rkistner** [facebook/Docusaurus#1183]
## 🐛 Bug Report

(Not sure if this should be a proposal instead).

When using both subfolders and versioning, document ids become quite confusing.

### Have you read the [Contributing Guidelines on issues]

Yes

## To Reproduce

1. Start with a file `docs/sub1/doc1.md`, with `id: doc1`. It is accessible as `/docs/sub1/doc1`, as expected.
2. Run `yarn docusaurus-version v2`.

## Expected behavior

I expect document id, path, sidebar reference and URL to follow a consistent pattern, instead of four different ones.

I would expect something like this:

```yaml
path: versions/v2/sub1/doc1.md
id: v2/sub1/doc1 # should be automatically inferred from the path, but that's another issue
sidebar: v2/sub1/doc1
url: /docs/sub1/doc1
versioned url: /docs/v2/sub1/doc1
```

_I would also expect the versioned URL to be available immediately, not only when the next version is published. But that's also another issue._

## Actual Behavior

```yaml
path: version-v2/sub1/doc1.md
id: version-v2-doc1
sidebar: version-v2-sub1/doc1
url: /docs/sub1/doc1
versioned url: /docs/v2/sub1/doc1
```

## Reproducible Demo

_TODO_
