### ISSUE TITLE
It is impossible to publish to GitHub pages if I doesn't set user name and e-mail globally in Git

### ISSUE THREAD

**Issue by daminort** [facebook/docusaurus#1771]
## 🐛 Bug Report

I doesn't have global Git setting regarding user name and e-mail.
I set git config locally only for this my Docusaurus project, but when I try to publish my project to GitHub Pages I get an error:
```
fatal: unable to auto-detect email address
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Remove your global Git settings for `user.name` and `user.email` (if any)
2. Try to publish by command `GIT_USER=<GIT_USER> CURRENT_BRUNCH=master npm run publish-gh-pages`

## Expected behavior

The website has been published and I see in the terminal
```
Website is live at: https://<GIT_USER>.github.io/<PROJECT_NAME>
```

## Actual Behavior

I get an error:
```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address
```

## Reproducible Demo

My example repo is available here: [data-caster-docs](https://github.com/daminort/data-caster-docs).
But you can reproduce this bug with any project, even with template from CLI.

## Potential Solution

Due to I don't want to set global Git config (for any my personal reasons),
I have changed the file `publish-gh-pages.js` a little bit in two places:
```
...
// When we want to do a cross repo publish (#717), we can allow publishing to the same branch.
const currentRepoUrl = shell
  .exec('git config --get remote.origin.url')
  .stdout.trim();
const crossRepoPublish = !currentRepoUrl.endsWith(
  `${ORGANIZATION_NAME}/${PROJECT_NAME}.git`,
);

// !!! changes start !!!
// when we use local user data for our repo
const localUserName = shell
  .exec('git config --local --get user.name')
  .stdout.trim();
const localUserEmail = shell
  .exec('git config --local --get user.email')
  .stdout.trim();
// !!! changes end !!!
...

shell.cd(path.join('build', `${PROJECT_NAME}-${DEPLOYMENT_BRANCH}`));
shell.exec('git add --all');

// !!! changes start !!!
// maybe we are using local user data, so let's try to set them locally too
if (localUserName && localUserEmail) {
  shell.exec(`git config user.name "${localUserName}"`);
  shell.exec(`git config user.email "${localUserEmail}"`);
}
// !!! changes end !!!
...
```

It resolved the issue for me.
If it will be needed I could make the pull-request with this fix

**Comment by endiliey** [comment]
its intended. we also explained in https://docusaurus.io/docs/en/publishing that u need to somehow set up the github auth. It might be unclear, accepting pr on docs for that.

**Comment by hatton** [comment]
It's not clear to me that the documentation does explain what is needed when using `docusaurus deploy` in a GH Action. I have GIT_USER and GIT_PASS set to a Personal Access Token, fine. But I'm also getting this other message like the original reporter here, which seems unrelated to github authentication:

```
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@fv-az4[53](https://github.com/sillsdev/notion-pull-sample-site/runs/6600086738?check_suite_focus=true#step:8:54)-7[61](https://github.com/sillsdev/notion-pull-sample-site/runs/6600086738?check_suite_focus=true#step:8:62).hss2zji4abbufegd5wcf2so25h.dx.internal.cloudapp.net>) not allowed
```
Here's what I tried to get around it, but it didn't work:

```
      - name: Identify to git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Build github pages branch
        env: 
          GIT_USER: ${{ secrets.GIT_USER_FOR_PUSH_TO_GH_PAGES_BRANCH }}
          GIT_PASS: ${{ secrets.PERSON_ACCESS_TOKEN_FOR_PUSH_TO_GH_PAGES_BRANCH }}
        run: yarn deploy
```

Confusingly, the docs currently talk about this Docusaurus Deploy, but then give an example GH Action that instead does an explicit `build` followed by `peaceiris/actions-gh-pages@v3`. I'll try that next.

**Comment by hatton** [comment]
Yeah, that works:

```
      - name: Build github pages branch
        run: yarn build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSON_ACCESS_TOKEN_FOR_PUSH_TO_GH_PAGES_BRANCH }}
          publish_dir: ./build
```
