### ISSUE TITLE
There is a space in the right of the page

### ISSUE THREAD

**Issue by blackredscarf** [facebook/docusaurus#1776]
There is a space in the right of the page when the width under 1115px. This space exists when initializing the project.

![](https://i.loli.net/2019/09/09/Nqw8HaSTU4GVr1L.png)

I try to change the CSS, but not help.

**Comment by blackredscarf** [comment]
I found that the page of Draft.js has the same problem.

![2019-09-11_214921.png](https://i.loli.net/2019/09/11/W9ACfOzwn4JqkXH.png)

**Comment by yangshun** [comment]
I managed to reproduce the error on smaller screens. It seems that the footer link widths are exceeding the grid column span, that's the cause of the issue. PRs are welcome!

**Comment by blackredscarf** [comment]
@yangshun Hello. I checked the footer, but cannot find out where exceeds. Can you tell me how can I fix it?

**Comment by yangshun** [comment]
The links within the footer. Try deleting them and see that it works

**Comment by blackredscarf** [comment]
@yangshun Thank you. I found it.

My temporary solution is adding the following CSS in `custom.css`.
```css
.nav-footer .sitemap a {
    color: rgba(255, 255, 255, 0.6);
    display: block;
    margin-top: 2px;
    margin-bottom: 2px;
    margin-left: -10px;
    margin-right: 0;
    padding: 3px 10px;
}
```
