### ISSUE TITLE
Add docs for cross-repo publishing using CircleCI

### ISSUE THREAD

**Issue by yechs** [facebook/docusaurus#1971]
## 📚 Documentation

Thanks to #764, we can publish the site to a different repo by setting `projectName` in `docusaurus.config.js` to the destination.

However, this behaves differently on CircleCI. The deployment script reads environment variable `CIRCLE_PROJECT_REPONAME`, which represents the name of the repository of the current project, and overrides the `projectName` configured in `docusaurus.config.js`

See https://github.com/facebook/docusaurus/blob/812a30be5727d88ae62a7c15473796a9b2bc1297/packages/docusaurus/src/commands/deploy.ts#L45

```javascript
const projectName = process.env.PROJECT_NAME ||
    process.env.CIRCLE_PROJECT_REPONAME ||
    siteConfig.projectName;
```

To correctly cross-repo publishing the site, the user will need to configure environment variables in CircleCI config

```yaml
- run:
  name: Deploy to GitHub Pages
  command: yarn run deploy
  # Set environment variables so that project is deployed correctly
  environment:
    GIT_USER: [git username]
    ORGANIZATION_NAME: Computerization
    PROJECT_NAME: computerization.github.io
```

I feel like this somehow needs to be documented so as not to confuse users using CircleCI

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
