### ISSUE TITLE
[v2] Colon in title or sidebar_label breaks markdown

### ISSUE THREAD

**Issue by SwaroopH** [facebook/docusaurus#2031]
## 🐛 Bug Report

Adding a colon (`:`) to `title` and/or `sidebar_label` content in a markdown document causes an error in v2 - works fine on v1. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## To Reproduce

(Write your steps here:)

1. Add a new markdown doc
2. Enter the following

```yaml
---
id: ev_basics_lesson
title: EthVigil Primer: Deploying and Interacting with smart contracts
sidebar_label: Lesson EV001: Deploying and Interacting with smart contracts
---
```

## Expected behavior

Should render the page normally

## Actual Behavior

`UnhandledPromiseRejectionWarning: YAMLException: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line`

## Reproducible Demo

https://github.com/SwaroopH/docusaurusv2-testing/tree/broken-title

Bug due to: https://github.com/SwaroopH/docusaurusv2-testing/blob/broken-title/docs/doc1.md
