### ISSUE TITLE
How to override infima variables

### ISSUE THREAD

**Issue by oriooctopus** [facebook/docusaurus#2577]
## ❓ Questions and Help

In my custom.css file, I can override the basic color variable such as `--ifm-color-primary`, but I can't seem to override the other variables such as `--ifm-heading-vertical-rhythm-bottom)`

Is this at all possible?

**Comment by lex111** [comment]
Sorry for late response.

Not all CSS vars of Infima are defined in the global scope, for example, to override the value for `--ifm-heading-vertical-rhythm-bottom`, you need do this in the proper CSS class:

```css
.markdown {
  --ifm-heading-vertical-rhythm-bottom: 2;
}
```
