### ISSUE TITLE
improvement(v2): typography

### ISSUE THREAD

**Issue by kripod** [facebook/docusaurus#2598]
## 🚀 Feature

The default settings for Infima provide tight line heights, which is hard to comprehend, especially on desktop. Also, the root font size is overridden by a small, pixel-based value, which is bad for accessibility.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Improve legibility and accessibility of the default theme.

## Implementation

```css
:root {
  --ifm-font-size-base: 100%;
  --ifm-code-font-size: 93.75%; /* 15/16, one px smaller than the base font */
  --ifm-line-height-base: 1.75; /* Instead of 1.5 */
  --ifm-leading-desktop: 1.25; /* Instead of 1.5 */
  --ifm-list-margin: var(--ifm-leading); /* Keep consistent with the leading */
}
```

## Comparison

![image](https://user-images.githubusercontent.com/14854048/79116926-ff927000-7d89-11ea-84db-5dadf8f85d15.png)

**Comment by yangshun** [comment]
Agreed. Will fix in Infima.

**Comment by kripod** [comment]
Also, please inherit the color of links for `<code>` elements, e.g. with:

```css
a code {
  color: inherit;
}
```

New vs. flawed approach:

![Link color comparison](https://user-images.githubusercontent.com/14854048/79640368-95b30580-8191-11ea-9670-1a4a0d901d36.png)
