### ISSUE TITLE
[v2] Text near code spans illegible with note admonitions in dark mode

### ISSUE THREAD

**Issue by kripod** [facebook/docusaurus#2609]
## 🐛 Bug Report

In dark mode, the text surrounding code spans may become illegible, as the code span's background gets mixed with the text color. For instance, the `,` after `breakpoints` is almost invisible below:

![image](https://user-images.githubusercontent.com/14854048/79277100-770af100-7ea9-11ea-845c-97f33b58155c.png)

Better results can be achieved by putting spaces near code spans – "( `breakpoints` , `shorthands` and `aliases` )" instead of "(`breakpoints`, `shorthands` and `aliases`)":

![image](https://user-images.githubusercontent.com/14854048/79277369-f26ca280-7ea9-11ea-8b38-2c45871c49ff.png)

However, a true fix would be making the background of code spans admonition-agnostic.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

Create an MDX-based page using the code below and turn on dark mode:

```mdx
:::note
Keeping the runtime as small as possible, only a few tokens (`breakpoints`, `shorthands` and `aliases`) are embedded into production JavaScript bundles. Other values can only be accessed exclusively for styling, as [shown below](#usage).
:::
```

## Expected behavior

The background color of code spans should depend on the underlying admonition background's color.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.50

## Reproducible Demo

https://github.com/kripod/glaze/tree/692afe15feed36201ee79c4201a87ff536606953/packages/website

Run `yarn develop` and then see http://localhost:3000/docs/getting-started#managing-design-tokens.

**Comment by kripod** [comment]
After inspecting [the code of Infima](https://unpkg.com/browse/infima@0.2.0-alpha.6/dist/css/default/default.css), I saw in lines 987–993 that secondary alerts are handled specially, causing the trouble described above:

```css
.alert.alert--secondary {
    --ifm-alert-color: --ifm-color-gray-900;
    color: var(--ifm-color-gray-900)
  }
.alert.alert--secondary a {
      color: var(--ifm-color-gray-900);
    }
```

As a quick fix, I suggest applying the following CSS, making secondary admonitions independent from the active color scheme:

```css
.alert.alert--secondary code {
  background: var(--ifm-color-gray-100);
}
```
