### ISSUE TITLE
v2 theme-classic `.contents` className is very generic and can easily clash with other libraries like monaco-editor

### ISSUE THREAD

**Issue by pbeshai** [facebook/docusaurus#2752]
## 🐛 Bug Report

Just trying to get started with docusaurus v2 and wanted to use the [monaco-editor](https://github.com/Microsoft/monaco-editor) (VS Code editor) to make a playground page, but I noticed the tooltips didn't render properly within it:

![image](https://user-images.githubusercontent.com/793847/82066825-c436da00-9684-11ea-989e-56514203f08e.png)

After some investigation, it became clear this is due to a clash between CSS class names `contents` from theme-classic and `contents` within monaco-editor itself:

![image](https://user-images.githubusercontent.com/793847/82066968-f0eaf180-9684-11ea-9155-f7696f974433.png)

From theme-classic:

```css
.contents {
    font-size: 0.8rem;
    margin-bottom: 0;
    padding-bottom: var(--ifm-contents-padding-vertical);
    padding-top: var(--ifm-contents-padding-vertical);
}
```

A solution that works for me is to add this CSS in my custom.css file:

```css
.monaco-editor .contents {
  font-size: inherit;
  margin-bottom: inherit;
  padding-top: inherit;
  padding-bottom: inherit;
}
```

However, I imagine adding playgrounds with monaco-editor will be a reasonably common thing to do, so it would be ideal to not have CSS clashes right from the get-go. Perhaps the class name from the theme could be prefixed to reduce the probability of clashes? e.g. `docu-contents` or similar.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Add monaco editor to a page and type the letter `t` to see a tooltip appear. Example page:

```js
import Editor from '@monaco-editor/react';
import Layout from '@theme/Layout';
import * as React from 'react';

function Playground() {
  return (
    <Layout title="Playground">
      <Editor height="90vh" language="javascript" />
    </Layout>
  );
}

export default Playground;
```

## Expected behavior

This tooltip would render properly without any customization.

## Actual Behavior

Tooltip renders with entries clipped due to padding set by `.contents`

## Your Environment

- Docusaurus version used: 2.0.0-alpha.54
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 81
- Operating system and version (desktop or mobile): Mac OS

```
    "@docusaurus/core": "^2.0.0-alpha.54",
    "@docusaurus/preset-classic": "^2.0.0-alpha.54",
    "@monaco-editor/react": "^3.3.0",
    "monaco-editor": "^0.20.0",
    "react": "^16.8.4",
    "react-dom": "^16.8.4"
```

## Reproducible Demo

https://github.com/pbeshai/github-issue-docusaurus-contents-clash

Go to playground page (/playground) and type `t` to reproduce
