### ISSUE TITLE
Import files to `theme-live-codeblock` scope

### ISSUE THREAD

**Issue by oze4** [facebook/docusaurus#2807]
## 🐛 Bug Report

Import statements in `theme-live-codeblock` not working.  I read the `react-live` docs and it does look like they do support importing modules - does docusaurus expose the needed scope?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Configure `theme-live-codeblock` according [to these instructions](https://v2.docusaurus.io/docs/markdown-features/#interactive-code-editor)
1. Install `@material-ui/core`
1. Create `file.mdx` attempt to import components from `@material-ui/core`
1. Attempted to import within `.mdx` file as well as the ` ``` jsx live ` block

## Expected behavior

Render the imported component

## Actual Behavior

 - When the import statement is at the top of `.mdx` (*keep in mind I can use the imported component within the .mdx file just fine, just can't use it within the ` ```jsx live ` block..*):

![image](https://user-images.githubusercontent.com/21092343/82743985-594a6a80-9d38-11ea-8ffd-fd89c4a8c016.png)

 - When the import statement is inside the ` ```jsx live ` block:

![image](https://user-images.githubusercontent.com/21092343/82743994-74b57580-9d38-11ea-91f5-a99d473bb545.png)

## Your Environment

- Docusaurus version used: 2.0.0-alpha.55
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node: v13.12.0, Firefox: 76.0.1
- Operating system and version (desktop or mobile): Catalina 10.15.4 

```javascript
// from package.json
"dependencies": {
  "@docusaurus/core": "^2.0.0-alpha.55",
  "@docusaurus/preset-classic": "^2.0.0-alpha.55",
  "@docusaurus/theme-live-codeblock": "^2.0.0-alpha.39",
  "@material-ui/core": "^4.10.0",
  "@material-ui/icons": "^4.9.1",
  "classnames": "^2.2.6",
},
```

## Reproducible Demo

 - [Demo 1](https://material-table-core.com/docs/highlights/highlight_actions/#demo-1)
 - [Demo 2](https://material-table-core.com/docs/highlights/highlight_actions/#demo-2)
 - [.mdx file](https://pastebin.com/fq6brFdB)

**Comment by oze4** [comment]
After browsing through the repo, it doesn't look like `docusaurus` lets you configure `react-live` scope.. 

As a workaround, this is what I did:

 - Copied the code from [Playground](https://github.com/facebook/docusaurus/blob/d910ff118ed9c72bb78c627a37d57500020caa50/packages/docusaurus-theme-live-codeblock/src/theme/Playground/index.js), [usePrismTheme](https://github.com/facebook/docusaurus/blob/d910ff118ed9c72bb78c627a37d57500020caa50/packages/docusaurus-theme-classic/src/theme/hooks/usePrismTheme.js), and [styles.module.css](https://github.com/facebook/docusaurus/blob/d910ff118ed9c72bb78c627a37d57500020caa50/packages/docusaurus-theme-live-codeblock/src/theme/Playground/styles.module.css) all to the same directory

<details>
<summary>Slightly modified <code>Playground</code></summary>

```javascript
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';

import {
  LiveProvider,
  LiveEditor,
  LiveError,
  LivePreview
} from 'react-live'

import classnames from 'classnames';
import usePrismTheme from './usePrismTheme.js';

import * as styles from './styles.module.css';

function Playground({children, /* theme, */ transformCode, ...props}) {
  const theme = usePrismTheme();

  return (
    <LiveProvider
      code={children.replace(/\n$/, '')}
      transformCode={transformCode || ((code) => `${code};`)}
      theme={theme}
      {...props}>
      <div
        className={classnames(
          styles.playgroundHeader,
          styles.playgroundEditorHeader,
        )}>
        Live Editor
      </div>
      <LiveEditor />
      <div
        className={classnames(
          styles.playgroundHeader,
          styles.playgroundPreviewHeader,
        )}>
        Result
      </div>
      <div className={styles.playgroundPreview}>
        <LivePreview />
        <LiveError />
      </div>
    </LiveProvider>
  );
}

export default Playground;
```
</details>

<details>
<summary>NOT modified <code>usePrismTheme</code></summary>

```javascript
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import defaultTheme from 'prism-react-renderer/themes/palenight';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import useThemeContext from '@theme/hooks/useThemeContext';

const usePrismTheme = () => {
  const {
    siteConfig: {
      themeConfig: {prism = {}},
    },
  } = useDocusaurusContext();
  const {isDarkTheme} = useThemeContext();
  const lightModeTheme = prism.theme || defaultTheme;
  const darkModeTheme = prism.darkTheme || lightModeTheme;
  const prismTheme = isDarkTheme ? darkModeTheme : lightModeTheme;

  return prismTheme;
};

export default usePrismTheme;
```

</details>


<details>
<summary>NOT modified <code>styles.module.css</code></summary>

```css
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

 .playgroundHeader {
  letter-spacing: 0.08rem;
  padding: 0.75rem;
  text-transform: uppercase;
  font-weight: bold;
}

.playgroundEditorHeader {
  background: var(--ifm-color-emphasis-600);
  color: var(--ifm-color-content-inverse);
}

.playgroundPreviewHeader {
  background: var(--ifm-color-emphasis-200);
  color: var(--ifm-color-content);
}

.playgroundPreview {
  border: 1px solid var(--ifm-color-emphasis-200);
  border-bottom-left-radius: var(--ifm-global-radius);
  border-bottom-right-radius: var(--ifm-global-radius);
  position: relative;
  padding: 1rem;
}
```

</details>

From there, I import the Playground into an .mdx file and it worked!  I did try to use `react-live` components on their own, which worked, but styling was not right.  That is why I copied those components - to keep styling.

#### `MyFile.mdx`:

```
---
id: some_id
title: My Live Code Demo 
---

import Playground from '../Playground';
import { Button } from '@material-ui/core';

### Custom components

<LiveCodeBlock scope={{ Button }}>
{`
function MyButton() {
  return <Button color="secondary" onClick={() => alert("Hello, world!")}>Click me</Button>
}
`}
</LiveCodeBlock>
```

Which works perfectly!

![image](https://user-images.githubusercontent.com/21092343/82745697-edbec800-9d4c-11ea-8b39-0d77f223d94d.png)
