### ISSUE TITLE
[infima] restyle admonitions

### ISSUE THREAD

**Issue by maximousblk** [facebook/docusaurus#2930]
## 💥 Proposal

The current (alpha56) admonitions do not look very good. Specially the "caution" admonition. Text on Yellow loses contrast in light mode and links using the default primary color lose contrast in "important" admonition.

And over all the colors are too bright for dark mode.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

### Pitch

I have experimented with some styles and created a demo. [[code](https://github.com/maximousblk/docusaurus-playground)]

Preview:

![84570593-11a18680-adac-11ea-9ab9-d488def89a42](https://user-images.githubusercontent.com/28438021/84570877-b40e3980-adad-11ea-9bbe-a4761924f2ae.jpg)

You can compare differences between the [new style](https://docusaurus-playground.vercel.app/docs/#admonitions) and the [current style](https://docusaurus-2.now-examples.now.sh/docs/doc1#admonitions).

The summary example is for #2924

**Comment by slorber** [comment]
so before we had:

![image](https://user-images.githubusercontent.com/749374/84662549-40d70580-af1c-11ea-837a-0be612660822.png)

![image](https://user-images.githubusercontent.com/749374/84662571-47fe1380-af1c-11ea-9a36-843627b08191.png)

after:

![image](https://user-images.githubusercontent.com/749374/84662743-81cf1a00-af1c-11ea-9e73-7ea0a1801530.png)

![image](https://user-images.githubusercontent.com/749374/84662777-898ebe80-af1c-11ea-8a72-fe9b44b4d479.png)

--- 

I like this new design, but fear that errors/warnings become less visible.

Wonder what others think.

**Comment by maximousblk** [comment]
If visibility is a concern then the v1 admonitions should work well.

![image](https://user-images.githubusercontent.com/28438021/84664774-a63aee80-af3c-11ea-833d-ad91d2b6be55.png)

I tried to recreate them but the colored background did not look very good in the dark mode (opinion). So I used the default background colors, but as you said, they became less visible. Then I opted for a color slightly off from the background which infima already had preset for (`--ifm-color-emphasis-100`).

**Comment by actual-size** [comment]
I like the new style, but I think doubling the left border would do a lot for visibility while still maintaining the style. Based on emulation, people with colour vision deficiencies will also have an easier time than with the thinner border.

**Comment by maximousblk** [comment]
I updated [the demo](https://docusaurus-playground.vercel.app/docs/#admonitions) according to @actual-size's idea any it certainly pops out more.

**Comment by slorber** [comment]
yes this is more visible

About the summary/details view, I liked the left border too, it seems you have removed it

**Comment by maximousblk** [comment]
@slorber yes that was certainly a mistake. It worked in my local environment but somehow broke in production.

I was trying to have some styles shared between the ther admonitions and the details admonition which I have reverted and it works now.

**Comment by slorber** [comment]
After discussions with @yangshun we'd like to update our admonitions styles

However Infima is not a public github repo for now, so the best option is that you give me your css and I update the styles there

**Comment by maximousblk** [comment]
@slorber That is a great news!

All I did was use infima's variables in the `custom.css` file to simulate what it should look like.

You can find the `custom.css` file [here](https://github.com/maximousblk/docusaurus-playground/blob/master/src/css/custom.css)

**Comment by markerikson** [comment]
FWIW, you can see how I restyled the admonitions for the Redux docs in this PR:

https://github.com/reduxjs/redux/pull/3740

Here's the specific file:

https://github.com/reduxjs/redux/blob/87c4edd77011f7f064d3653c595a5168558c9a5f/website/src/css/custom.css

Example appearances:

![image](https://user-images.githubusercontent.com/1128784/85235273-ab3aea80-b3e1-11ea-8b43-7250a15c3af5.png)

![image](https://user-images.githubusercontent.com/1128784/85235276-b130cb80-b3e1-11ea-8a71-873cadd32d7b.png)

**Comment by slorber** [comment]
Thanks @markerikson , that looks quite similar to the restyle proposal here

Do you have a page where these admonitions are used? I only found some pages with notes un purple.

BTW the style of Redux and Redux toolkit doc seems different regarding admonitions :)

**Comment by markerikson** [comment]
@slorber That PR isn't merged yet, and that's where I updated our DS version and added that admonitions styling.  So, the PR preview link I sent is the only place where it's visible yet.

RTK's docs were still on alpha.43 until I pushed some doc updates yesterday, and we don't actually use "admonitions" in the RTK docs yet - just styled blockquotes.

**Comment by slorber** [comment]
Thanks,

Noticed you removed the dark mode in this PR (wanted to check the admonitions in dark mode). Curious if it's related to a D2 issue, or an explicit choice (might be related to https://github.com/facebook/docusaurus/pull/2939 ?)

**Comment by markerikson** [comment]
I didn't "remove" dark mode, I just created this branch months ago before dark mode actually got enabled in the Redux docs site :)

**Comment by slorber** [comment]
@maximousblk your link doesn't work anymore, can you host it somewhere else please? https://github.com/maximousblk/docusaurus-playground/blob/master/src/css/custom.css

@yangshun can we safely change the styles of infima alerts without affecting other FB projects?

Anyone wants to work on this?

Seems we need to change alerts in Infima, + the style preset of this repo: https://github.com/elviswolcott/remark-admonitions/blob/master/styles/infima.css

@elviswolcott what's the motivation to handle the preset on your repo instead of letting us maintain it?

**Comment by maximousblk** [comment]
@slorber so sorry for that. here is the css:

<details><summary>CSS</summary>

```css
/* stylelint-disable docusaurus/copyright-header */
/**
 * Any CSS included here will be global. The classic template
 * bundles Infima by default. Infima is a CSS framework designed to
 * work well for content-centric websites.
 */

/* You can override the default Infima variables here. */
:root {
  --ifm-color-primary: #fa7548;
  --ifm-color-primary-dark: #fa6938;
  --ifm-color-primary-darker: #f95d29;
  --ifm-color-primary-darkest: #f95219;
  --ifm-color-primary-light: #fa8158;
  --ifm-color-primary-lighter: #fb8d67;
  --ifm-color-primary-lightest: #fb9877;
  --ifm-code-font-size: 95%;

  --ifm-color-success: var(--ifm-color-success-light);
  --ifm-color-info: var(--ifm-color-info-light);
  --ifm-color-warning: var(--ifm-color-warning-light);
  --ifm-color-danger: var(--ifm-color-danger-light);

  --ifm-global-radius: 0.2rem;

  --ra-admonition-icon-color: var(--ifm-alert-border-color);
  --ifm-alert-color: var(--ifm-alert-border-color);
}

.docusaurus-highlight-code-line {
  background-color: rgb(72, 77, 91);
  display: block;
  margin: 0 calc(-1 * var(--ifm-pre-padding));
  padding: 0 var(--ifm-pre-padding);
}

.alert {
  background-color: var(--ifm-background-surface-color);
  border-color: var(--ifm-alert-border-color);
  color: var(--ifm-font-color-base);
}

.alert a {
  color: var(--ifm-color-primary);
  text-decoration: var(--ifm-link-decoration);
}

.alert .admonition-heading {
  color: var(--ifm-font-color-base);
}

.admonition-icon svg {
  fill: var(--ifm-alert-border-color);
  stroke: var(--ifm-alert-border-color);
  margin-right: 12px;
}

a:hover {
  text-decoration: underline;
}

.admonition {
  border: none;
  background-color: var(--ifm-color-emphasis-100);
  border-radius: 0;
  border-left-width: 0.3rem;
  border-left-style: solid;
  border-color: var(--ifm-alert-border-color);
}

details {
  background-color: var(--ifm-color-emphasis-100);
  border-radius: 0;
  border-left-width: 0.3rem;
  border-left-style: solid;
  border-color: var(--ifm-color-emphasis-900);
  padding: var(--ifm-alert-padding-vertical) var(--ifm-alert-padding-horizontal);
  margin-bottom: 1em;
}

summary {
  outline: none;
  font-weight: bold;
  cursor: pointer;
}

details[open] summary {
  margin-bottom: 1em;
}

.alert--secondary {
  --ifm-alert-background-color: var(--ifm-color-emphasis-900);
  --ifm-alert-border-color: var(--ifm-color-emphasis-900);
}
```
