### ISSUE TITLE
Document how to use Prism Plugins / add Prism diff-highlight plugin

### ISSUE THREAD

**Issue by rrousselGit** [facebook/docusaurus#3318]
## 📚 Documentation

Prism comes with the ability to use prism plugins to add extra functionalities – such as [diff-highlight](https://prismjs.com/plugins/diff-highlight/) to combine the syntax highlighting of a language with the `diff` feature.

It is currently unclear how to enable prism plugins.

I've tried playing with `swizzle` to extract the code-highlighting renderer, but failed to implement this feature.

Cross-reference:
- https://docusaurus-2.netlify.app/feedback/p/include-prism-diff-highlight
- https://stackoverflow.com/questions/62754505/how-to-use-prism-plugins-with-docusaurus-v2?noredirect=1

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by slorber** [comment]
We use react-prism-renderer and it does not seem to support the ability to add such plugin, so unfortunately we can't support this unless they add support, but that seems not planned:
https://github.com/FormidableLabs/prism-react-renderer/issues/2

**Comment by Repraance** [comment]
I found a way to implement diff-highlight using magic comments.

The problem is the line number is wrong, but we can hide it.

Example:

<img width="982" alt="image" src="https://github.com/facebook/docusaurus/assets/9989327/5617cd6d-eca5-42b7-b7af-5c7a8f4a43a7">


markdown
```
```tsx
// diff-remove
<a href={`/${lng}/some-path`}>
// diff-remove
location.href = `/some-path`

// diff-add
<a href={'/some-path'}>
// diff-add
location.href = `/some-path`
```
```




For `docusaurus.config.js`, set
```js
const config = {
  prism: {
    magicComments: [
      {
        className: 'code-block-diff-add-line',
        line: 'diff-add'
      },
      {
        className: 'code-block-diff-remove-line',
        line: 'diff-remove'
      }
    ]
  }
}
```

And add custom css
```css
.code-block-diff-add-line {
  background-color: #ccffd8;
  display: block;
  margin: 0 -40px;
  padding: 0 40px;
}

.code-block-diff-add-line::before {
  position: absolute;
  left: 8px;
  padding-right: 8px;
  content: '+';
}

.code-block-diff-remove-line {
  background-color: #ffebe9;
  display: block;
  margin: 0 -40px;
  padding: 0 40px;
}

.code-block-diff-remove-line::before {
  position: absolute;
  left: 8px;
  padding-right: 8px;
  content: '-';
}

/**
 * use magic comments to mark diff blocks
 */
pre code:has(.code-block-diff-add-line) {
  padding-left: 40px!important;
}

pre code:has(.code-block-diff-remove-line) {
  padding-left: 40px!important;
}
```

**Comment by thefat32** [comment]
Implemented diff-highlight compatible with docusaurus ([prism-react-renderer](https://www.npmjs.com/package/prism-react-renderer))

You need to [swizzle ](https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages) in your docusaurus repo:

```sh
yarn swizzle @docusaurus/theme-classic prism-include-languages
```

- `docusaurus.config.ts` (Example for using diff-ts)

```ts
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ["diff", "diff-ts"],
    },
```

-  `prism-include-languages.ts`

```ts
import siteConfig from "@generated/docusaurus.config";
import type * as PrismNamespace from "prismjs";
import { diffHighlight } from "./prism-diff-highlight.js";
import "./prism-diff-highlight.css";

const DIFF_LANGUAGE_REGEX = /^diff-([\w-]+)/i;

export default function prismIncludeLanguages(
  PrismObject: typeof PrismNamespace
): void {
  const {
    themeConfig: { prism },
  } = siteConfig;
  const { additionalLanguages } = prism as { additionalLanguages: string[] };

  // Prism components work on the Prism instance on the window, while prism-
  // react-renderer uses its own Prism instance. We temporarily mount the
  // instance onto window, import components to enhance it, then remove it to
  // avoid polluting global namespace.
  // You can mutate PrismObject: registering plugins, deleting languages... As
  // long as you don't re-assign it
  globalThis.Prism = PrismObject;

  additionalLanguages.forEach((lang) => {
    const langMatch = DIFF_LANGUAGE_REGEX.exec(lang);
    if (!langMatch) {
      require(`prismjs/components/prism-${lang}`); // not a language specific diff
    } else {
      const diffLanguage = langMatch[1];
      if (
        !PrismObject.languages[diffLanguage] &&
        !additionalLanguages.includes(diffLanguage)
      )
        console.warn(
          `You need to add prism language ${diffLanguage} to use ${lang}`
        );
      PrismObject.languages[lang] = PrismObject.languages.diff;
    }
  });

  diffHighlight(PrismObject);

  delete globalThis.Prism;
}
```

- `prism-diff-highlight.js`

```js
/* eslint-disable no-undef */
export function diffHighlight(Prism) {
  if (Prism) {
    const LANGUAGE_REGEX = /^diff-([\w-]+)/i;

    Prism.hooks.add("after-tokenize", function (env) {
      let diffLanguage;
      let diffGrammar;

      if (env.language !== "diff") {
        const langMatch = LANGUAGE_REGEX.exec(env.language);
        if (!langMatch) {
          return; // not a language specific diff
        }

        diffLanguage = langMatch[1];
        diffGrammar = Prism.languages[diffLanguage];
      } else {
        return;
      }

      const newTokens = [];
      env.tokens.forEach((token) => {
        if (token.type === "unchanged") {
          newTokens.push(
            ...Prism.tokenize(
              token.content.map((subToken) => subToken.content).join(""),
              diffGrammar
            )
          );
        } else if (token.type === "deleted-sign") {
          token.alias = ["diff-highlight-deleted"];
          token.content = [
            token.content[0],
            ...Prism.tokenize(token.content[1].content, diffGrammar),
          ];
          newTokens.push(token);
        } else if (token.type === "inserted-sign") {
          token.alias = ["diff-highlight-inserted"];
          newTokens.push(token);
        } else if (typeof token === "string") {
          newTokens.push(token);
        }
      });
      env.tokens = newTokens;
    });
  }
}
```

- `prism-diff-highlight.css`
```css
code .token.diff-highlight-deleted {
	background-color: rgba(255, 0, 0, .1);
}

code .token.diff-highlight-inserted {
	background-color: rgba(0, 255, 128, .1);
}
```

- Result:

![image](https://github.com/facebook/docusaurus/assets/10998637/ed3962db-1ed7-4704-9199-d3aa9765f5f8)


You can add whatever other language you want in `additionalLanguages`:

```ts
      additionalLanguages: ["diff", "diff-ts", "powershell", "diff-powershell"],
```

![image](https://github.com/facebook/docusaurus/assets/10998637/9ed3eabf-4c96-47eb-844c-b8d6466171aa)


NOTE FOR DEVS/INTERESTE PEOPLE:

Prism plugins do not work with [prism-react-renderer](https://www.npmjs.com/package/prism-react-renderer) because they rely in other hooks that are not called. They only call hooks `"before-tokenize"` and `"after-tokenize"`. This reimplementation uses `"after-tokenize"` to edit tokens generated by [prism-react-renderer tokenizer](https://github.com/FormidableLabs/prism-react-renderer/blob/master/packages/prism-react-renderer/src/components/useTokenize.ts).

In theory every plugin could be implemented using those hooks to work with prism-react-renderer

**Comment by uc-kywong** [comment]
![image](https://github.com/facebook/docusaurus/assets/146920777/2f0b6a41-d184-4f2e-bff4-9468e818f28e)




I think you can write you own component to display `diff` like github.

```bash
$ npm install --save react-diff-view
```

I am using version 3.2.1. (https://www.npmjs.com/package/react-diff-view)

---

Create your component

`src/components/CustomDiff/CustomDiff.js`
```js
import {Decoration, Diff, Hunk, parseDiff} from "react-diff-view";
import 'react-diff-view/style/index.css';
import './CustomDiff.css';


export default function CustomDiff({diffText}) {
  const files = parseDiff(diffText);
  return (
    <div>
      {files.map((
        {hunks, newPath, oldPath}, i) =>
        <Diff
          renderToken={(token) => token.content}
          key={i}
          viewType="split"
          diffType=""
          hunks={hunks}
        >
          {
            hunks => hunks.map(hunk => {
              return <>
                <Decoration key={'decoration-' + hunk.content}>
                  {`${oldPath}`}
                </Decoration>
                <Decoration key={'decoration-' + hunk.content}>
                  {`${newPath} - ${hunk.content}`}
                </Decoration>
                <Hunk key={hunk.content} hunk={hunk} />
              </>
            }
          )}
        </Diff>
      )}
    </div>
  );
}
```

Css for your component.

`src/components/CustomDiff/CustomDiff.css`
```css
:root {
    --ifm-table-border-width: 0px;
}

table {
    display: table;
}

.diff-code {
    font-size: 85%;
}
```

---

How to use it in markdown?

```mdx
import CustomDiff from "@site/src/components/CustomDiff/CustomDiff";


<CustomDiff diffText={`
diff --git a/package.json b/package.json
--- a/package.json	(revision c38f44524532d3a87986bfa4b9b8b82d8f0e29a0)
+++ b/package.json	(revision 93e71e98e457dae88403cdf204a8f4a85f60cc42)
@@ -1,6 +1,6 @@
 {
   "name": "SSO-Admin-UI",
-  "version": "1.0.0",
+  "version": "2.0.0-alpha.0",
   "license": "MIT",
   "scripts": {
     "start": "ng serve -o -c=dev --port=8500 --baseHref=/",
`}
/>
```
