### ISSUE TITLE
CSS + SVG: can't use background-image: url('/mySvg.svg');

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3566]
## 🐛 Bug Report

**Problem:**

The following svg  usage in css URL does not work

```css
body {
  background-image: url('../../static/img/docusaurus.svg');
}
```

This leads to code being in the CSS instead of the SVG url.

![image](https://user-images.githubusercontent.com/749374/95595808-e32b7380-0a4c-11eb-90ac-9a3d9c02734e.png)

---

**Solution:**

This happens because webpack css-loader convert urls to require calls, and  we have a svg loader that  convert svg require calls to React components.

Webpack doc says it's possible to disable this url to require conversion on a per url basis through config: https://webpack.js.org/loaders/css-loader/#url

Note it's also possible to use  the webpack inline require syntax to force a specific loader. To convert svg to url we can force the "file-loader" (or url-loader to have base64)

```css
body {
  background-image: url('~!file-loader!../../static/img/docusaurus.svg');
}
```

---

**Note**: this is not really a bug, but added it to issues for discoverability, as I'm not sure we should document this behavior on Docusaurus website, yet it's likely to happen to other users.
