### ISSUE TITLE
Published to subfolder rather than root

### ISSUE THREAD

**Issue by IniZio** [facebook/Docusaurus#358]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

(OS, Node, npm, yarn)

OS: Ubuntu 17.10
Node: 8.7.0
npm: 5.6.0
yarn: 1.3.2

### Steps to Reproduce

(Write your steps here:)

1. Set up .travis.yml as follows:
```
language: node_js

branches:
  only:
    - develop
    - feat/initial-setup

cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules

notifications:
  email: false

node_js:
  - '8'

script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - cd website && npm install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
```
2. Push to Github develop branch

### Expected Behavior

Expected the built files to be pushed to root of master branch of organization.github.io

### Actual Behavior

The build and push did not fail, but it ended up in a 'organization.github.io' folder of organization.github.io repo rather than in root.

### Reproducible Demo

Repo: https://github.com/clippedjs/clippedjs.github.io

Source code is at feat/initial-setup branch, the 833cc6665cf42526ff53a3d6b8900a1bed1f04a0 commit.

Enter the GH_NAME, GH_EMAIL, GH_TOKEN with github username, email and personal access token respectively in Travis.

Push to travis
