### ISSUE TITLE
Custom local fonts do not load.

### ISSUE THREAD

**Issue by emilnewel** [facebook/docusaurus#3788]
## 🐛 Bug Report

Custom **(Locally stored)** fonts do not load. I have seen that there is documentation for importing Google Fonts, but have not yet seen anything that can help with fonts that are stored locally. 

I am probably calling the fonts incorrectly, but due to no documentation being present for fonts that are stored locally, and no errors showing up I have no clue why my fonts will not load.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Clone git@github.com:emilnewel/docusaurus-issue.git
2. Install with yarn on npm. 
3. Run project with npm start.
4. See that the font does not change to the desired font. (Setimo in my case)

## Expected behavior

The big red text on the front page to be in Setimo font.

## Actual Behavior

Font is just some basic system font. 

![image](https://user-images.githubusercontent.com/31038044/99792645-4bc34100-2b1f-11eb-87ee-5ce25f2931d1.png)

## Your Environment

- Docusaurus version used: `2.0.0-alpha.68`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): `Chrome 86.0.4240.198` and `Node v14.5.0`
- Operating system and version (desktop or mobile): Mac OS 11.0.1 Big Sur.
- Fonts are stored in static/ folder
- Extended webpack is stored under plugins/my-loaders/ and is also set in docusaurus.config.js

## Reproducible Demo

https://github.com/emilnewel/docusaurus-issue

**Comment by andrewtruong** [comment]
You can load fonts by dropping the `.woff` into `static`, and adding this to your `custom.css`

```css
@font-face {
  font-family: "JetBrains Mono Regular";
  src: url('/static/JetBrainsMono-Regular.woff') format('woff');
}

:root {
  --ifm-font-family-monospace: "JetBrains Mono Regular";
  --ifm-font-family-base: 'Noto Sans JP';
}
```

**Comment by emilnewel** [comment]
@andrewtruong, this does nto seem to work for me.

![image](https://user-images.githubusercontent.com/31038044/100017064-3fb2da00-2dd2-11eb-9c0c-fd7349726042.png)

As you can see in the image, according to chrome the font is "Setimo" but this is not the correct font.

This is my current folder structure :
```
website
│      
└───src
│   │   pages
│   │   ...
│   │
│   └───css
│       │  custom.scss
│   
└───static
    │   Setimo_Rg.ttf
```

Inside of custom.scss I have:

```scss
@font-face {
  font-family: "Setimo";
  src: url("/static/Setimo_Rg.ttf") format("ttf");
  font-weight: 400;
  font-style: normal;
}

:root {
  --ifm-font-family-base: "Setimo";
}
```

Any ideas? 🤔
