### ISSUE TITLE
Improve blog layout

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#4083]
## 🐛 Bug Report

The current blog layout is not ideal, particularly on large screens where blog titles wrap unnecessarily.

![image](https://user-images.githubusercontent.com/749374/105370762-34c6cb00-5c04-11eb-9679-596abe79a1dd.png)

Also the spacing is not very good when there's a blog post list scrollbar

![image](https://user-images.githubusercontent.com/749374/105371757-35ac2c80-5c05-11eb-9741-f268afe54c0a.png)

The ReactNative site has a better blog layout using custom CSS, but it's not ideal either to write this CSS as we have to target classes of the Infima grid system in a fragile way

![image](https://user-images.githubusercontent.com/749374/105370915-5f188880-5c04-11eb-8291-bbf90ddae457.png)

For example, I used a similar solution for the Jest v2 website:

```scss
.main-wrapper.blog-wrapper .container .row {

  // Blog post list
  .col.col--2:first-child {
    --ifm-col-width: 22%;
    div[class^='sidebar'] {
      padding-right: 1rem;
    }
  }

  // Center
  .col.col--8 {
    --ifm-col-width: 62%;
    @media only screen and (max-width: 996px) {
      --ifm-col-width: 100% !important;
    }
  }

  // TOC
  .col.col--2:last-child {
    --ifm-col-width: 16%;
  }
}
```

We should rather adopt current ReactNative design in the default Docusaurus blog layout design in future versions, and stop using a basic css grid for that as we want the sides to grow when space is available.

cc @lex111 @Simek
