### ISSUE TITLE
Sometimes the color is missing when running `yarn build`

### ISSUE THREAD

**Issue by Kimi-Gao** [facebook/docusaurus#4319]
## 🐛 Bug Report

Sometimes the color is missing when running `yarn build`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## To Reproduce

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Write your steps here:)

1. Add below code in `custom.css`
```css
.menu .menu__link.menu__link--active:not(.menu__link--sublist) {
  border: 1px solid rgba(167, 167, 167, 0.2);
}
```
1. `yarn build`
1. Search `.menu .menu__link.menu__link--active:not(.menu__link--sublist)` in `build` directory

## Expected behavior

```css
.menu .menu__link.menu__link--active:not(.menu__link--sublist) {
  border: 1px solid rgba(167, 167, 167, 0.2);
}
```

## Actual Behavior

![image](https://user-images.githubusercontent.com/12554487/109488420-82b2d680-7ac0-11eb-9938-887fadd670bf.png)

## Your Environment

- Public source code: 
- Public site url:
- Docusaurus version used: 2.0.0-alpha.70
- Environment name and version : node v14.15.5 (npm v6.14.11)
- Operating system and version (desktop or mobile): macOS big sur 11.1

## Reproducible Demo

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

https://codesandbox.io/s/interesting-night-ze576?file=/src/css/custom.css
