### ISSUE TITLE
dark mode: Callouts/admonitions

### ISSUE THREAD

**Issue by armano2** [facebook/docusaurus#4321]
## 🐛 Bug Report

Dark mode is missing default styles for admonitions/alerts

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

https://v2.docusaurus.io/docs/markdown-features#calloutsadmonitions in dark mode

![image](https://user-images.githubusercontent.com/625469/109509955-bf230a00-7aa1-11eb-9f38-c5fda332b369.png)

## Expected behavior

there should be predefined styles for callouts in dark mode

as workaround i added to my styles, but those styles should be predefined
```css
html[data-theme='dark'] .alert--secondary {
  --ra-admonition-icon-color: var(--ifm-color-emphasis-900);
  --ifm-alert-background-color: var(--ifm-color-emphasis-100);
  --ifm-alert-border-color: var(--ifm-color-emphasis-200);
  --ifm-alert-color: var(--ifm-color-emphasis-900);
}
```
![image](https://user-images.githubusercontent.com/625469/109509928-b92d2900-7aa1-11eb-9106-2058ec680916.png)

## Actual Behavior

there is no syles for dark mode callouts

## Your Environment

- Public source code: this repo
- Public site url: https://v2.docusaurus.io/docs/markdown-features#calloutsadmonitions 
- Docusaurus version used: master
- Environment name and version: unrelated
- Operating system and version (desktop or mobile): all
