### ISSUE TITLE
GitHub Actions deployment error: "Git push failed"

### ISSUE THREAD

**Issue by mrousavy** [facebook/docusaurus#4336]
## 🐛 Bug Report

I am trying to use GitHub actions to automatically build my documentation from the `main` branch (`docs/` folder) and deploy it to the `gh-pages` branch.

I've followed [the official guide](https://v2.docusaurus.io/docs/deployment#deploying-to-github-pages), but can't seem to get it working.

```
Success! Generated static files in build. Use `npm run serve` to test your build locally.

Site successfully built in locale=en
CMD: git clone https://git@github.com/cuvent/react-native-vision-camera.git react-native-vision-camera-gh-pages (code=0)
CMD: git checkout origin/gh-pages (code=0)
CMD: git checkout -b gh-pages (code=0)
CMD: git branch --set-upstream-to=origin/gh-pages (code=0)
CMD: git rm -rf . (code=0)
CMD: git add --all (code=0)
CMD: git commit -m "Deploy website - based on a97a3cf6ec9602e116bdd774c50c85c1f8d89097" (code=0)
CMD: git push --force origin gh-pages (code=128)
/home/runner/work/react-native-vision-camera/react-native-vision-camera/docs/node_modules/@docusaurus/core/lib/commands/deploy.js:145
                throw new Error('Error: Git push failed');
                ^

Error: Error: Git push failed
    at /home/runner/work/react-native-vision-camera/react-native-vision-camera/docs/node_modules/@docusaurus/core/lib/commands/deploy.js:145:23
    at copyDirItems (/home/runner/work/react-native-vision-camera/react-native-vision-camera/docs/node_modules/fs-extra/lib/copy/copy.js:171:21)
    at /home/runner/work/react-native-vision-camera/react-native-vision-camera/docs/node_modules/fs-extra/lib/copy/copy.js:183:14
    at /home/runner/work/react-native-vision-camera/react-native-vision-camera/docs/node_modules/graceful-fs/polyfills.js:247:20
    at FSReqCallback.oncomplete (fs.js:156:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

This is my GitHub Action:

```yml
name: Build Documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
      - name: Release to GitHub Pages
        env:
          USE_SSH: false
          GIT_USER: git
          CURRENT_BRANCH: main
          DEPLOYMENT_BRANCH: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          cd docs
          yarn install --frozen-lockfile
          yarn deploy
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yea

## Your Environment

- Public source code: https://github.com/cuvent/react-native-vision-camera
- Public site url: https://github.com/cuvent/react-native-vision-camera
- Docusaurus version used: 2.0.0-alpha.70

## Reproducible Demo

See [my repo](https://github.com/cuvent/react-native-vision-camera), especially the [docusaurus config file](https://github.com/cuvent/react-native-vision-camera/blob/main/docs/docusaurus.config.js) and the [github action](https://github.com/cuvent/react-native-vision-camera/blob/main/.github/workflows/build-docs.yml).

And [here's](https://github.com/cuvent/react-native-vision-camera/runs/2022038429?check_suite_focus=true) the log output from the GitHub action.

Note that it does work if I run it locally, so I'm guessing something in the action isn't correctly configured/authenticated...

**Comment by mrousavy** [comment]
I think this happens because I set `USE_SSH: false`. But if I use `USE_SSH: true`, the git command fails at git clone....

* [Here's](https://github.com/cuvent/react-native-vision-camera/runs/2022240319) the GitHub action log output with `USE_SSH: false`
* [Here's](https://github.com/cuvent/react-native-vision-camera/runs/2021930307) the GitHub action log output with `USE_SSH: true`

**Comment by mrousavy** [comment]
Why does it even try to git clone again? When this code runs it already is in the git repo...

**Comment by slorber** [comment]
can you try the new workflow introduced by this PR?
https://github.com/facebook/docusaurus/pull/4263

I'm not too familiar with GH action, would have to inspect the code. more carefully to understand this problem

**Comment by armano2** [comment]
there should not be a need for additional token configuration as checkout already provides this functionality

https://github.com/actions/checkout#push-a-commit-using-the-built-in-token

```bash
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
```

**Comment by mrousavy** [comment]
@armano2 I'm pretty sure that won't work as I have already tried that before. I will check again later though.

@slorber so that's just moving the ssh-agent step into a dedicated action right?

I have currently got it working like this: 

```yml
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          CURRENT_BRANCH: main
          DEPLOYMENT_BRANCH: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          yarn install --frozen-lockfile
          cd docs
          yarn install --frozen-lockfile
          yarn deploy
```

I'm not sure if that's the best, fastest or safest way, but it works. I'll try to remove all of the SSH stuff so I don't need to worry about the private/public key+secret and just try to use checkout@v2 like @armano2 commented.

**Comment by mrousavy** [comment]
@armano2 okay so I just tried it like this:

```yml
  gh-release:
    if: github.event_name != 'pull_request'
    name: Build & Release Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: github-actions
          CURRENT_BRANCH: main
          DEPLOYMENT_BRANCH: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn install --frozen-lockfile
          cd docs
          yarn install --frozen-lockfile
          yarn deploy
```

and it did not work. It fails at git clone again:

![Screenshot 2021-03-09 at 14 13 33](https://user-images.githubusercontent.com/15199031/110475838-a3db7e80-80e1-11eb-9bbe-bbcb704d55d1.png)

**Comment by polarathene** [comment]
The checkout action default is a shallow clone of the commit. You may need to pull the full history to properly be in sync when doing a push.

```yml
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
```

Alternatively, as I have noticed (with a different deployment approach), `gh-pages` branch may not share a common commit if it was never branched off. For me this causes some issues with my Git GUI, I wouldn't be surprised if it causes any issues with regular `git` CLI either, unless you clone the branch separately.

Anyway, I started out with the approach that Docusaurus originally documented and found it over-complicated for deploying Github Pages vs other platforms. You can use a Github Action for deployment like this (no SSH keys required):

```yml
- name: 'Your build steps'
  run: |
    date > generated.txt
    yarn install --frozen-lockfile
    cd docs
    yarn install --frozen-lockfile
    yarn build

- name: 'Deploy to Github Pages'
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./docs/build
    user_name: 'github-actions[bot]'
    user_email: '41898282+github-actions[bot]@users.noreply.github.com'
```

Note I changed `yarn deploy` to `yarn build`. This is assuming your docs output a build to `./docs/build`. I'm not sure what the earlier `date` and `yarn install` commands are for prior to changing to docs dir, as those won't be part of the deployment?
