### ISSUE TITLE
Allow hiding of single articles via frontmatter

### ISSUE THREAD

**Issue by Zenahr** [facebook/docusaurus#5882]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

While writing docs it often is necessary to completely hide references to articles temporarily (in-between publishing doc updates).

It is possible to fully customize what articles show up via the sidebar config file, but AFAIK it is not possible to hide single articles via the YAML frontmatter in such a manner:

```yaml
---
sidebar_position: 1
title: some title
hidden: true
---
```

other option names could be:

- `publish`
- `draft`

In essence what this would do is not take the markdown file into account when generating the static HTML or when deploying the webapp.

### Motivation

This helps in simplifying documentation management in general for larger projects. It often is the case that writers draft new documents but these new docs shouldn't show up online. This could be solved via separating the new work into its own branch but this is rather clumsy.

### API design

```yaml
---
sidebar_position: 1
title: some title
hidden: true
---
```

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.
