### ISSUE TITLE
Cannot use hot reloading in Docker

### ISSUE THREAD

**Issue by cod3rshotout** [facebook/docusaurus#6722]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm trying to run docusaurus over docker and use the hot reload feature so I don't need to recompile each time the project, but for some reason when I do a change the project doesn't recompile

### Steps to reproduce

1. Create a new project and install docusaurus, I have the version 2.0.0-beta.15
2. Create this docker-compose:

```
  version: "3"

  services:
    docusaurus:
      build: .
      expose:
        - 3000
        - 35729
      ports:
        - 3000:3000
        - 35729:35729
      volumes:
        - ./docs:/app/docs
        - ./website/blog:/app/website/blog
        - ./website/core:/app/website/core
        - ./website/i18n:/app/website/i18n
        - ./website/pages:/app/website/pages
        - ./website/static:/app/website/static
        - ./website/sidebars.json:/app/website/sidebars.json
        - ./website/siteConfig.js:/app/website/siteConfig.js
      working_dir: /app/website
```

3. Create this Dockerfile:

```
FROM node:lts

WORKDIR /app/website

EXPOSE 3000 35729
COPY ./docs /app/docs
COPY ./website /app/website
RUN yarn install

CMD ["yarn", "start", "--host", "0.0.0.0", "--port", "35729"]
```

4. Now run `docker-compose up --build -d`
5. Try to change a file within docs, nothing happen

### Expected behavior

When an update is made, the code should reload automatically

### Actual behavior

When an update is made no changes are reflected on the live site

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.
