### ISSUE TITLE
Incorrect instruction for GitHub Actions

### ISSUE THREAD

**Issue by arifszn** [facebook/docusaurus#6775]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

The instruction for [Triggering deployment with GitHub Actions](https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions) assumes the website source resides in the main branch of your repository (the source branch is main), under a folder called `website/`. 
![image](https://user-images.githubusercontent.com/45073703/155871461-50e7a2cb-2775-4552-a249-199d55f83447.png)

But the GitHub action files do not have any setting to reflect this folder structure. The action files will only work if the source resides in the root instead of the folder `website/`.

```yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
```

I fixed the action files but then the `cache: yarn` throws this error `Error: Dependencies lock file is not found in /home/runner/work/docusaurus/docusaurus. Supported file patterns: yarn.lock`.

![image](https://user-images.githubusercontent.com/45073703/155871587-7dddc700-9a0d-4b3d-8e13-73f1000e1f3f.png)

### Self-service

- [X] I'd be willing to address this documentation request myself.
