### ISSUE TITLE
Button style css `:where` selector is experimental feature and broken in old browsers

### ISSUE THREAD

**Issue by guyskk** [facebook/docusaurus#7617]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Button style css `:where` selector is experimental feature and broken in many browsers. Can reproduce by visit  https://docusaurus.io/ in some old version browser, the "Get Started" and "Try a Demo" button style is broken.

![6321655221679_ pic](https://user-images.githubusercontent.com/6367792/173620600-1edea1c0-f2d6-4d4c-95d9-9d50681acbc1.jpg)

And I checked the css file, seems no needs to use `:where` selector, change them to simple css selector can fix the issue.

```css
:where(.button--primary) {
    --ifm-button-background-color: var(--ifm-color-primary);
    --ifm-button-border-color: var(--ifm-color-primary);
}

:where(.button--primary):not(.button--outline):hover {
    --ifm-button-background-color: var(--ifm-color-primary-dark);
    --ifm-button-border-color: var(--ifm-color-primary-dark)
}

:where(.button--secondary) {
    --ifm-button-background-color: var(--ifm-color-secondary);
    --ifm-button-border-color: var(--ifm-color-secondary)
}

:where(.button--secondary):not(.button--outline):hover {
    --ifm-button-background-color: var(--ifm-color-secondary-dark);
    --ifm-button-border-color: var(--ifm-color-secondary-dark)
}
```

See also: https://caniuse.com/?search=where

### Reproducible demo

https://docusaurus.io/

### Steps to reproduce

1. Visit https://docusaurus.io/ in chrome older than version 87, or other old version browsers
2. Check the button style

### Expected behavior

Expect the Button style is same as the style show in latest browser.

### Actual behavior

The Button style not work, no background color.

### Your environment

- Public source code: N/A
- Public site URL: https://docusaurus.io/
- Docusaurus version used: 2.0.0-beta.21
- Environment name and version: the browser in Wechat, it seems based on an old version chrome.
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Android

### Self-service

- [ ] I'd be willing to fix this bug myself.
