### ISSUE TITLE
CSS gets stripped out, whitespace gets removed in production build

### ISSUE THREAD

**Issue by vaibhavshn** [facebook/docusaurus#7753]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

CSS is getting stripped in some places when you create a production build.

In dev server, css is applied properly.

### Production build

<img width="277" alt="image" src="https://user-images.githubusercontent.com/6205961/178101755-b78b292f-718b-43bb-8ae2-ef442bcf533a.png">

`display: inline-flex` isn't applied here.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/6205961/178101784-1f1b9cfc-bfa0-4595-9355-40c36680837c.png">

### Dev Server

<img width="573" alt="image" src="https://user-images.githubusercontent.com/6205961/178101808-33e39e07-39ba-4c9d-a78c-5c794e8d307d.png">

`display: inline-flex` is applied here.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/6205961/178101817-916f6058-6d17-46da-b627-c71750a183d7.png">

### CSS Code used

```css

.sections-menu-trigger {
  flex: 1 !important;
  all: unset;
  display: inline-flex;
  background-color: var(--docs-color-background-100) !important;
  color: var(--docs-color-text);
  height: 48px;
  border-radius: 6px;
  align-items: center;
  justify-content: space-between;

  box-sizing: border-box;
  border: none;
  outline: none;

  cursor: pointer;

  box-sizing: border-box;
  border: 1px solid var(--docs-color-background-200);
}
```

This can be fixed adding `!important` to the `display` property.

Also note that the `!important` values also have the same issue, which I fixed by adding `!important`.

Might be a postcss autoprefixer issue probably.

### Steps to reproduce

1. Create custom styles targeting a specific classname, like the code I used above.
2. Check with dev server, all of it is applied.
3. Check prod build, some of it isn't applied.

### Expected behavior

CSS shouldn't get stripped.

### Actual behavior

CSS is getting stripped in production build.

### Your environment

- Public source code:
- Public site URL: https://dyte-docs-beta.vercel.app/react-ui-kit
- Docusaurus version used: 2.0.0-beta.22
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Monterey

### Self-service

- [ ] I'd be willing to fix this bug myself.
