### ISSUE TITLE
Algolia mobile search modal responsiveness

### ISSUE THREAD

**Issue by Etesam913** [facebook/docusaurus#7831]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

The Algolia mobile search modal does not account for scrolling.

### Video:

https://user-images.githubusercontent.com/55665282/181079882-c0864d11-894a-48c9-8dec-3503b7b83321.mov

I believe that this css needs to be added to fix this:
```css
@media (max-width: 750px) {
  .DocSearch-Container {
      position: fixed !important;
  }
}
```
