### ISSUE TITLE
Setup your Netlify CMS / Decap CMS in a self-hosted Gitlab

### ISSUE THREAD

**Issue by stouch** [facebook/docusaurus#9040]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

I spent hours to setup my Netlify (setup on my self-managed gitlab) on Docusaurus. Here is how I finally made it up :

1. Create your Gitlab Application  (check non-confidential / protected branches etc (see Gitlab docs))
2. Get your pcke token
3. Create config.yml in static/admin : 
```yml
backend:
  name: gitlab
  repo: repo/project
  branch: your_branch
  auth_type: pkce
  app_id: <YOUR_APP_ID>
  api_root: https://gitlab.yourdomain.com/api/v4
  base_url: https://gitlab.yourdomain.com
  auth_endpoint: oauth/authorize
  accept_roles:
    - admin
    - editor

# when using the default proxy server port (for local dev)
local_backend: true

locale: fr

media_folder: "static/img"
public_folder: "/img"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: docs
    label: Docs
    label_singular: Doc
    folder: docs
    create: true
    nested:
      depth: 4 
      summary: '{{title}}' 
    fields:
      - label: Sidebar position
        name: sidebar_position
        widget: number
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
      - label: Image
        name: image
        widget: 'image'
        allow_multiple: false
      - label: Body
        name: body
        widget: markdown
    sortableFields: ["title", "sidebar_position"]
    extension: md
    format: frontmatter
    editor:
      preview: false
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }  
```
4. Create index.html in static/admin : 
```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="noindex" />
  <title>Content Manager</title>
</head>
<body>
  <!-- Include the script that builds the page and powers Decap CMS -->
  <script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
</body>
</html>
```

5. Run `npm run start` 

6. In local, to emulate your file-system direcotry instead of remote git file-system, run, from the project root : 
```
npx netlify-cms-proxy-server
```
 
7. Go to /admin 

### Self-service

- [ ] I'd be willing to address this documentation request myself.
